@startuml Alert_Tasks_Diagram

entity "0" as 0 {
  operator : string
  sensorTag : string
  threshold : int
  thresholdType : string
}

entity "Alert Tasks" as Alert_Tasks {
  _id : ObjectId
  toUser : string
  condition : list
  type : string
  dueTimeFromPosting : string
  autoCalling : boolean
  escalations : object
  heading : object
  description : object
  subTasks : list
  metadata : object
  plantId : ObjectId
  attachedTickets : list
  isOpen : boolean
  ccUsers : list
  observationTime : string
  primaryUser : object
  resolutionFreq : string
  equipments : object
  issueType : list
}

entity "condition" as condition {
  0 : object
}

entity "escalations" as escalations {
  Level 1 : object
  Level 2 : object
  Level 3 : object
}

entity "Level 1" as Level_1 {
  time : string
  group : string
}

entity "Level 2" as Level_2 {
  time : string
  group : string
}

entity "Level 3" as Level_3 {
  time : string
  group : string
}

entity "heading" as heading {
  eng : string
  hindi : string
}

entity "description" as description {
  eng : string
  hind : string
}

entity "subTasks" as subTasks {
  name : string
  namehindi : string
}

entity "metadata" as metadata {
  createdBy : string
  createdAt : string
}

entity "ccUsers" as ccUsers {
  _id : ObjectId
  role : string
  name : string
  email : string
  number : string
  forid : ObjectId
  password : string
  plantId : list
  userStatus : string
}

entity "plantId" as plantId {
  _id : ObjectId
}

entity "primaryUser" as primaryUser {
  _id : ObjectId
  forWho : string
  plantId : list
  name : string
  number : string
  email : string
  forid : ObjectId
  role : string
  password : string
  userStatus : unknown
}

entity "equipments" as equipments {
  id : string
  nickName : string
  type : string
}

' // Relationships
Alert_Tasks ||--o{ condition : has_condition
condition ||--|| 0 : has_0
Alert_Tasks ||--|| escalations : has_escalations
escalations ||--|| Level_1 : has_Level 1
escalations ||--|| Level_2 : has_Level 2
escalations ||--|| Level_3 : has_Level 3
Alert_Tasks ||--|| heading : has_heading
Alert_Tasks ||--|| description : has_description
Alert_Tasks ||--o{ subTasks : has_subTasks
Alert_Tasks ||--|| metadata : has_metadata
Alert_Tasks ||--o{ ccUsers : has_ccUsers
ccUsers ||--o{ plantId : has_plantId
Alert_Tasks ||--|| primaryUser : has_primaryUser
primaryUser ||--o{ plantId : has_plantId
Alert_Tasks ||--|| equipments : has_equipments
@enduml