@startuml attachments_Diagram

entity "attachments" as attachments {
  _id : ObjectId
  attachmentLink : string
  filename : string
  expireAt : unknown
  mimetype : string
  createdAt : object
  updatedAt : object
  __v : int
}

entity "createdAt" as createdAt {
}

entity "updatedAt" as updatedAt {
}

' // Relationships
attachments ||--|| createdAt : has_createdAt
attachments ||--|| updatedAt : has_updatedAt
@enduml