@startuml bidirectionalhistories_Diagram

entity "bidirectionalhistories" as bidirectionalhistories {
  _id : ObjectId
  plantId : ObjectId
  hmiButtons : list
  equipmentId : string
  created_at : object
  events : list
  sensorId : ObjectId
  initiated : boolean
  acknowledged : boolean
  ongoing : boolean
  underProcess : boolean
  successFull : boolean
  expiryMins : int
  terminated : boolean
  userName : string
  __v : int
}

entity "hmiButtons" as hmiButtons {
  _id : ObjectId
  plantId : ObjectId
  equipmentId : string
  hmiPrefix : string
  sensorId : ObjectId
  __v : int
  hmiTag : string
  trackingSensor : ObjectId
}

entity "created at" as created_at {
}

entity "events" as events {
  userId : ObjectId
  command : string
  ipAddr : string
  browserDetails : string
  timestamp : object
  type : string
  heading : string
  success : boolean
  _id : ObjectId
}

entity "timestamp" as timestamp {
}

' // Relationships
bidirectionalhistories ||--o{ hmiButtons : has_hmiButtons
bidirectionalhistories ||--|| created_at : has_created_at
bidirectionalhistories ||--o{ events : has_events
events ||--|| timestamp : has_timestamp
@enduml