@startuml CHOKE_POINT_CONFIG2_Diagram

entity "CHOKE POINT CONFIG2" as CHOKE_POINT_CONFIG2 {
  _id : objectId
  layoutId : objectId
  __v : int
  nodes : object
}

entity "NODES" as NODES {
  Equalization Tank1 : object
  Pump2 : object
  Pump1 : object
  Pump3 : object
  Pump4 : object
  Pump5 : object
  Pump6 : object
  Pump7 : object
  Pump8 : object
  Pump9 : object
  Pump10 : object
  Pump11 : object
  Pump12 : object
  Pump13 : object
  Pump14 : object
  Pump15 : object
  Pump16 : object
  Pump17 : object
  Pump18 : object
  Pump19 : object
  Pump20 : object
  Pump21 : object
  Pump24 : object
  Pump22 : object
  Pump23 : object
  Blower1 : object
  Blower2 : object
  MGF1 : object
  ACF1 : object
  Agitator1 : object
  Flowmeter1 : object
  Motorized Valve14 : object
  Motorized Valve13 : object
  Flowmeter2 : object
}

entity "EQUALIZATION TANK1" as EQUALIZATION_TANK1 {
  64510b95bf14bbb5792b543e : list
}

entity "PUMP2" as PUMP2 {
}

entity "PUMP1" as PUMP1 {
}

entity "PUMP3" as PUMP3 {
  64510b95bf14bbb5792b5444 : list
}

entity "PUMP4" as PUMP4 {
  64510b95bf14bbb5792b5447 : list
}

entity "PUMP5" as PUMP5 {
  64510b95bf14bbb5792b544d : list
}

entity "PUMP6" as PUMP6 {
  64510b95bf14bbb5792b5450 : list
}

entity "PUMP7" as PUMP7 {
  64510b95bf14bbb5792b5453 : list
}

entity "PUMP8" as PUMP8 {
  64510b95bf14bbb5792b5456 : list
}

entity "PUMP9" as PUMP9 {
  64510b95bf14bbb5792b5459 : list
}

entity "PUMP10" as PUMP10 {
  64510b95bf14bbb5792b545c : list
}

entity "PUMP11" as PUMP11 {
  64510c3abf14bbb5792b5465 : list
}

entity "PUMP12" as PUMP12 {
  64523f39bf14bbb5792b57d0 : list
}

entity "PUMP13" as PUMP13 {
  64523f39bf14bbb5792b57d2 : list
}

entity "PUMP14" as PUMP14 {
  64523f39bf14bbb5792b57d6 : list
}

entity "PUMP15" as PUMP15 {
  64523f39bf14bbb5792b57db : list
}

entity "PUMP16" as PUMP16 {
  645241f7bf14bbb5792b57dd : list
}

entity "PUMP17" as PUMP17 {
  645241f7bf14bbb5792b57e1 : list
}

entity "PUMP18" as PUMP18 {
  645241f7bf14bbb5792b57e1 : list
}

entity "PUMP19" as PUMP19 {
  645241f7bf14bbb5792b57e3 : list
}

entity "PUMP20" as PUMP20 {
  645241f7bf14bbb5792b57e0 : list
}

entity "PUMP21" as PUMP21 {
  645241f7bf14bbb5792b57e7 : list
}

entity "PUMP24" as PUMP24 {
  64525c5fbf14bbb5792b582a : list
}

entity "PUMP22" as PUMP22 {
  64524fd1bf14bbb5792b57eb : list
}

entity "PUMP23" as PUMP23 {
  64524fd1bf14bbb5792b57f2 : list
}

entity "BLOWER1" as BLOWER1 {
  64524fd1bf14bbb5792b57ed : list
}

entity "BLOWER2" as BLOWER2 {
  64524fd1bf14bbb5792b57ee : list
}

entity "MGF1" as MGF1 {
  64525954bf14bbb5792b5826 : list
}

entity "ACF1" as ACF1 {
  64525954bf14bbb5792b5827 : list
}

entity "AGITATOR1" as AGITATOR1 {
  64525c5fbf14bbb5792b582e : list
}

entity "FLOWMETER1" as FLOWMETER1 {
  64561597bf14bbb5792b5f91 : list
}

entity "MOTORIZED VALVE14" as MOTORIZED_VALVE14 {
  6458bf61bf14bbb5792b6392 : list
}

entity "MOTORIZED VALVE13" as MOTORIZED_VALVE13 {
  6458bf61bf14bbb5792b6391 : list
}

entity "FLOWMETER2" as FLOWMETER2 {
  64561597bf14bbb5792b5f93 : list
}

' // Relationships
CHOKE_POINT_CONFIG2 ||--|| NODES : has_nodes
NODES ||--|| EQUALIZATION_TANK1 : has_Equalization Tank1
NODES ||--|| PUMP2 : has_Pump2
NODES ||--|| PUMP1 : has_Pump1
NODES ||--|| PUMP3 : has_Pump3
NODES ||--|| PUMP4 : has_Pump4
NODES ||--|| PUMP5 : has_Pump5
NODES ||--|| PUMP6 : has_Pump6
NODES ||--|| PUMP7 : has_Pump7
NODES ||--|| PUMP8 : has_Pump8
NODES ||--|| PUMP9 : has_Pump9
NODES ||--|| PUMP10 : has_Pump10
NODES ||--|| PUMP11 : has_Pump11
NODES ||--|| PUMP12 : has_Pump12
NODES ||--|| PUMP13 : has_Pump13
NODES ||--|| PUMP14 : has_Pump14
NODES ||--|| PUMP15 : has_Pump15
NODES ||--|| PUMP16 : has_Pump16
NODES ||--|| PUMP17 : has_Pump17
NODES ||--|| PUMP18 : has_Pump18
NODES ||--|| PUMP19 : has_Pump19
NODES ||--|| PUMP20 : has_Pump20
NODES ||--|| PUMP21 : has_Pump21
NODES ||--|| PUMP24 : has_Pump24
NODES ||--|| PUMP22 : has_Pump22
NODES ||--|| PUMP23 : has_Pump23
NODES ||--|| BLOWER1 : has_Blower1
NODES ||--|| BLOWER2 : has_Blower2
NODES ||--|| MGF1 : has_MGF1
NODES ||--|| ACF1 : has_ACF1
NODES ||--|| AGITATOR1 : has_Agitator1
NODES ||--|| FLOWMETER1 : has_Flowmeter1
NODES ||--|| MOTORIZED_VALVE14 : has_Motorized Valve14
NODES ||--|| MOTORIZED_VALVE13 : has_Motorized Valve13
NODES ||--|| FLOWMETER2 : has_Flowmeter2
@enduml