@startuml CompleteSystemErd
' !include alertTasks.puml
!include Alert_Tasks.puml
' !include apilogs.puml
' !include attachments.puml
' !include bidirectionalhistories.puml
' !include caches.puml
' !include callLogs.puml
' !include chokePointConfig.puml
' !include chokePointConfig2.puml
' !include cleared_date.puml
' !include communicationComponents.puml
' !include companies.puml
' !include customFormulas.puml
' !include dashboardClusters.puml
' !include dashboardEmailConfigs.puml
' !include dashboardPageHistories.puml
' !include dashboardPages.puml
' !include dataBreakEvents.puml
' !include Data_Input_Backup.puml
' !include Data_Input_Form.puml
' !include emailLogs.puml
' !include errorLogsBackup.puml
' !include Escalation_Heirarchy.puml
' !include Firebase_Token.puml
' !include Fixed_Tasks_1.puml
' !include flocsamples.puml
' !include formulaAudits.puml
' !include formulas.puml
' !include Form_Data.puml
' !include globalFormulasAndVariables.puml
' !include HmiButtons.puml
' !include hmis.puml
' !include hyperFormulas.puml
' !include insightComponents.puml
' !include insights_templates.puml
' !include Inventory.puml
' !include inventoryDIForm.puml
' !include inventoryMigrationLogs.puml
' !include Inventory_Management.puml
' !include labTestDIForm.puml
' !include layoutDiagrams.puml
' !include LayoutPaths.puml
' !include Layouts.puml
' !include Live_Tasks_1.puml
' !include maintenanceDIForm.puml
' !include manualAlerts.puml
' !include Master.puml
' !include newDashboardPages.puml
' !include newUsers.puml
' !include newWorkspaces.puml
' !include notifications.puml
' !include oldbidirectionalhistories.puml
' !include OldInventory.puml
' !include One_Time_Tasks.puml
!include persistentnotifications.puml
!include plantFormulasAndVars.puml
!include plantimages.puml
!include PlantInventoryConfigStorage.puml
!include plantLayoutDiagram.puml
!include Plants.puml
!include plantsFeatureAuth.puml
!include Plant_Config.puml
!include plcs.puml
!include Remarks.puml
!include Roles.puml
!include rosters.puml
!include roster_schedules.puml
!include sensorHistory.puml
!include SensorLists.puml
!include sensorOffSets.puml
!include sensors.puml
!include sensorSettings.puml
!include sharedDashboard.puml
!include skill_managements.puml
!include smsLogs.puml
!include Solution.puml
!include Solutions.puml
!include SSEConnections.puml
!include StoreItems.puml
!include Stores.puml
!include streamDIForm.puml
!include tags.puml
!include taskComponents.puml
!include taskCounts.puml
!include tasks.puml
!include task_logs.puml
!include task_templates.puml
!include tests.puml
!include tickets.puml
!include timeFrames.puml
!include Time_Line_Backup.puml
!include Total_Hours_Run.puml
!include triggerComponents.puml
!include triggers.puml
!include twilioCalls.puml
!include twillioCalls.puml
!include useraddeditems.puml
!include userGroups.puml
!include userGroup_user_role.puml
!include userGroup_workspace_asset_user_role.puml
!include Users.puml
!include waterQualityDIForm.puml
!include whatsappLogs.puml
!include whatsappTemplates.puml
!include WidgetAnalysisHistory.puml
!include widgets.puml
!include workflows.puml
!include workspaceAlerts.puml
!include workspaceFormulas.puml
!include workspaceFormulaSensors.puml
!include workspaces.puml

@enduml
