@startuml companies_Diagram

entity "companies" as companies {
  _id : ObjectId
  companyName : string
  companyDescription : string
  companyAddress : string
  tags : list
  contactDetails : list
  createdAt : object
  updatedAt : object
  __v : int
}

entity "contactDetails" as contactDetails {
  fullName : string
  phoneNumber : string
  emailId : string
  designation : string
  comments : string
  _id : ObjectId
}

entity "createdAt" as createdAt {
}

entity "updatedAt" as updatedAt {
}


' Relationships
companies ||--o{ contactDetails : has_contactDetails
companies ||--|| createdAt : has_createdAt
companies ||--|| updatedAt : has_updatedAt
@enduml