@startuml CUSTOM_FORMULAS_Diagram

entity "CUSTOM FORMULAS" as CUSTOM_FORMULAS {
  _id : objectId
  plantId : objectId
  formulas : list
}

entity "FORMULAS" as FORMULAS {
  lhs : string
  rhs : string
  unit : string
  isLhsFixed : boolean
  order : int
}

' // Relationships
CUSTOM_FORMULAS ||--o{ FORMULAS : has_formulas
@enduml