@startuml customFormulas_Diagram

entity "customFormulas" as customFormulas {
  _id : ObjectId
  plantId : ObjectId
  formulas : list
}

entity "formulas" as formulas {
  lhs : string
  rhs : string
  unit : string
  isLhsFixed : boolean
  order : int
}


' Shared Plant entity
entity "Plants" as Plants {
  _id : ObjectId
}

' Relationships
customFormulas }o--|| Plants : refers_to
customFormulas ||--o{ formulas : has_formulas
@enduml