@startuml dashboardClusters_Diagram

entity "dashboardClusters" as dashboardClusters {
  _id : ObjectId
  name : string
  plantId : ObjectId
  defaultDashboardPageId : ObjectId
  dashboardPages : list
  subDashboardClusters : list
  createdBy : string
  deleted : boolean
}

entity "subDashboardClusters" as subDashboardClusters {
  name : string
  dashboardClusterId : ObjectId
}


' Shared Plant entity
entity "Plants" as Plants {
  _id : ObjectId
}

' Relationships
dashboardClusters }o--|| Plants : refers_to
dashboardClusters ||--o{ subDashboardClusters : has_subDashboardClusters
@enduml