@startuml DASHBOARD_EMAIL_CONFIGS_Diagram

entity "DASHBOARD EMAIL CONFIGS" as DASHBOARD_EMAIL_CONFIGS {
  _id : objectId
  clusterId : objectId
  dashboardPageId : objectId
  usersOrUserGroups : list
  createdBy : objectId
  createdAt : object
  updatedAt : object
  __v : int
}

entity "USERS OR USER GROUPS" as USERS_OR_USER_GROUPS {
  id : objectId
  type : string
  dailyEmail : boolean
  weeklyEmail : boolean
  monthlyEmail : boolean
  _id : objectId
}

entity "CREATED AT" as CREATED_AT {
}

entity "UPDATED AT" as UPDATED_AT {
}

' // Relationships
DASHBOARD_EMAIL_CONFIGS ||--o{ USERS_OR_USER_GROUPS : has_usersOrUserGroups
DASHBOARD_EMAIL_CONFIGS ||--|| CREATED_AT : has_createdAt
DASHBOARD_EMAIL_CONFIGS ||--|| UPDATED_AT : has_updatedAt
@enduml