@startuml DASHBOARD_CLUSTERS_Diagram

entity "DASHBOARD CLUSTERS" as DASHBOARD_CLUSTERS {
  _id : objectId
  name : string
  plantId : objectId
  defaultDashboardPageId : objectId
  dashboardPages : list
  subDashboardClusters : list
  createdBy : string
  deleted : boolean
}

entity "SUB DASHBOARD CLUSTERS" as SUB_DASHBOARD_CLUSTERS {
  name : string
  dashboardClusterId : objectId
}

' // Relationships
DASHBOARD_CLUSTERS ||--o{ SUB_DASHBOARD_CLUSTERS : has_subDashboardClusters
@enduml