@startuml dashboardPageHistories_Diagram

entity "dashboardPageHistories" as dashboardPageHistories {
  _id : ObjectId
  plantType : list
  plantId : unknown
  pageConfig : object
  historyOf : ObjectId
  __v : int
}

entity "pageConfig" as pageConfig {
  pageName : string
  plantName : string
  showEmbeddedLinks : boolean
  embeddedLinks : list
  public : boolean
  defaultTimeInDays : int
  defaultTimeRangeSettings : object
  defaultGranularitySettings : object
  createdBy : ObjectId
  lastUpdateInfo : object
  data : list
  _id : ObjectId
}

entity "defaultTimeRangeSettings" as defaultTimeRangeSettings {
  unit : string
  unitMultiplier : int
  timeRangeInMins : int
  timeRangeType : string
  startTime : object
  endTime : object
}

entity "startTime" as startTime {
}

entity "endTime" as endTime {
}

entity "defaultGranularitySettings" as defaultGranularitySettings {
  unit : string
  unitMultiplier : int
  granularityInMins : int
}

entity "lastUpdateInfo" as lastUpdateInfo {
  lastUpdated : unknown
  lastUpdater : ObjectId
}

entity "data" as data {
  widgets : list
  background : string
  showWidgetCluster : boolean
  clusterName : string
  _id : ObjectId
}

entity "widgets" as widgets {
  _id : string
  widgetType : string
  widgetOrigin : string
  checked : boolean
  heading : object
  font : object
  widgetOriginId : string
  dashboardPageId : string
}

entity "heading" as heading {
  english : string
  hindi : string
}

entity "font" as font {
  family : string
  color : string
  size : string
}


' Relationships
dashboardPageHistories ||--|| pageConfig : has_pageConfig
pageConfig ||--|| defaultTimeRangeSettings : has_defaultTimeRangeSettings
defaultTimeRangeSettings ||--|| startTime : has_startTime
defaultTimeRangeSettings ||--|| endTime : has_endTime
pageConfig ||--|| defaultGranularitySettings : has_defaultGranularitySettings
pageConfig ||--|| lastUpdateInfo : has_lastUpdateInfo
pageConfig ||--o{ data : has_data
data ||--o{ widgets : has_widgets
widgets ||--|| heading : has_heading
widgets ||--|| font : has_font
@enduml