@startuml DASHBOARD_PAGE_HISTORIES_Diagram

entity "DASHBOARD PAGE HISTORIES" as DASHBOARD_PAGE_HISTORIES {
  _id : objectId
  plantType : list
  plantId : unknown
  pageConfig : object
  historyOf : objectId
  __v : int
}

entity "PAGE CONFIG" as PAGE_CONFIG {
  pageName : string
  plantName : string
  showEmbeddedLinks : boolean
  embeddedLinks : list
  public : boolean
  defaultTimeInDays : int
  defaultTimeRangeSettings : object
  defaultGranularitySettings : object
  createdBy : objectId
  lastUpdateInfo : object
  data : list
  _id : objectId
}

entity "DEFAULT TIME RANGE SETTINGS" as DEFAULT_TIME_RANGE_SETTINGS {
  unit : string
  unitMultiplier : int
  timeRangeInMins : int
  timeRangeType : string
  startTime : object
  endTime : object
}

entity "START TIME" as START_TIME {
}

entity "END TIME" as END_TIME {
}

entity "DEFAULT GRANULARITY SETTINGS" as DEFAULT_GRANULARITY_SETTINGS {
  unit : string
  unitMultiplier : int
  granularityInMins : int
}

entity "LAST UPDATE INFO" as LAST_UPDATE_INFO {
  lastUpdated : unknown
  lastUpdater : objectId
}

entity "DATA" as DATA {
  widgets : list
  background : string
  showWidgetCluster : boolean
  clusterName : string
  _id : objectId
}

entity "WIDGETS" as WIDGETS {
  _id : string
  widgetType : string
  widgetOrigin : string
  checked : boolean
  heading : object
  font : object
  widgetOriginId : string
  dashboardPageId : string
}

entity "HEADING" as HEADING {
  english : string
  hindi : string
}

entity "FONT" as FONT {
  family : string
  color : string
  size : string
}

' // Relationships
DASHBOARD_PAGE_HISTORIES ||--|| PAGE_CONFIG : has_pageConfig
PAGE_CONFIG ||--|| DEFAULT_TIME_RANGE_SETTINGS : has_defaultTimeRangeSettings
DEFAULT_TIME_RANGE_SETTINGS ||--|| START_TIME : has_startTime
DEFAULT_TIME_RANGE_SETTINGS ||--|| END_TIME : has_endTime
PAGE_CONFIG ||--|| DEFAULT_GRANULARITY_SETTINGS : has_defaultGranularitySettings
PAGE_CONFIG ||--|| LAST_UPDATE_INFO : has_lastUpdateInfo
PAGE_CONFIG ||--o{ DATA : has_data
DATA ||--o{ WIDGETS : has_widgets
WIDGETS ||--|| HEADING : has_heading
WIDGETS ||--|| FONT : has_font
@enduml