@startuml Data_Input_Form_Diagram

entity "Data Input Form" as Data_Input_Form {
  _id : ObjectId
  plantId : ObjectId
  form : object
}

entity "form" as form {
  Water Quality Test Result : list
  Process Observation : list
  Maintenance : list
  Lab Test : list
  Inventory : object
}

entity "Water Quality Test Result" as Water_Quality_Test_Result {
  title : string
  min : int
  max : int
  checked : boolean
  type : string
  range : boolean
}

entity "Process Observation" as Process_Observation {
  type : string
  title : string
  checked : boolean
  options : list
}

entity "Maintenance" as Maintenance {
  title : string
  type : string
  checked : boolean
}

entity "Inventory" as Inventory {
  Chemicals : list
  Consumables : list
  Electrical Spare List : list
  Mechanical Spare List : list
  Tool List (Electrical & Mechanical) : list
  Tool for Cleaning : list
}

entity "Chemicals" as Chemicals {
  title : string
  min : int
  checked : boolean
  type : string
}

entity "Consumables" as Consumables {
  title : string
  min : int
  checked : boolean
  type : string
}

' // Relationships
Data_Input_Form ||--|| form : has_form
form ||--o{ Water_Quality_Test_Result : has_Water Quality Test Result
form ||--o{ Process_Observation : has_Process Observation
form ||--o{ Maintenance : has_Maintenance
form ||--|| Inventory : has_Inventory
Inventory ||--o{ Chemicals : has_Chemicals
Inventory ||--o{ Consumables : has_Consumables
@enduml