@startuml EMAIL_LOGS_Diagram

entity "EMAIL LOGS" as EMAIL_LOGS {
  _id : objectId
  from : string
  to : string
  subject : string
  message : string
  libResponse : list
  serviceType : string
  code : string
  errorDetails : unknown
  status : string
  createdAt : object
  updatedAt : object
  __v : int
}

entity "LIB RESPONSE" as LIB_RESPONSE {
  statusCode : int
  body : string
  headers : object
}

entity "HEADERS" as HEADERS {
  server : string
  date : string
  content-length : string
  connection : string
  x-message-id : string
  access-control-allow-origin : string
  access-control-allow-methods : string
  access-control-allow-headers : string
  access-control-max-age : string
  x-no-cors-reason : string
  strict-transport-security : string
  content-security-policy : string
  cache-control : string
  x-content-type-options : string
  referrer-policy : string
}

entity "CREATED AT" as CREATED_AT {
}

entity "UPDATED AT" as UPDATED_AT {
}

' // Relationships
EMAIL_LOGS ||--o{ LIB_RESPONSE : has_libResponse
LIB_RESPONSE ||--|| HEADERS : has_headers
EMAIL_LOGS ||--|| CREATED_AT : has_createdAt
EMAIL_LOGS ||--|| UPDATED_AT : has_updatedAt
@enduml