@startuml ERROR_LOGS_BACKUP_Diagram

entity "ERROR LOGS BACKUP" as ERROR_LOGS_BACKUP {
  _id : objectId
  errorMsg : string
  topic : string
  functionName : string
  fileName : string
  time : string
}

@enduml