@startuml Escalation_Heirarchy_Diagram

entity "Escalation Heirarchy" as Escalation_Heirarchy {
  _id : ObjectId
  escalation : object
  plantId : ObjectId
}

entity "escalation" as escalation {
  Escalation Level 1 : list
  Escalation Level 2 : list
  Escalation Level 3 : list
  Emergency Group : list
  Email Group : list
}

entity "Escalation Level 1" as Escalation_Level_1 {
  _id : ObjectId
}

entity "Escalation Level 2" as Escalation_Level_2 {
  _id : ObjectId
}

entity "Escalation Level 3" as Escalation_Level_3 {
  _id : ObjectId
}

entity "Emergency Group" as Emergency_Group {
  _id : ObjectId
}

entity "Email Group" as Email_Group {
  _id : ObjectId
}

' // Relationships
Escalation_Heirarchy ||--|| escalation : has_escalation
escalation ||--o{ Escalation_Level_1 : has_Escalation Level 1
escalation ||--o{ Escalation_Level_2 : has_Escalation Level 2
escalation ||--o{ Escalation_Level_3 : has_Escalation Level 3
escalation ||--o{ Emergency_Group : has_Emergency Group
escalation ||--o{ Email_Group : has_Email Group
@enduml