@startuml Fixed_Tasks_1_Diagram

entity "Fixed Tasks 1" as Fixed_Tasks_1 {
  _id : ObjectId
  toUser : string
  recurringDays : list
  weeks : list
  recurringTimes : string
  dueTimeFromPosting : string
  escalations : object
  heading : object
  description : object
  subTasks : list
  plantId : ObjectId
}

entity "escalations" as escalations {
  Level 1 : object
  Level 2 : object
  Level 3 : object
}

entity "Level 1" as Level_1 {
  time : string
  group : string
}

entity "Level 2" as Level_2 {
  time : string
  group : string
}

entity "Level 3" as Level_3 {
  time : string
  group : string
}

entity "heading" as heading {
  eng : string
  hindi : string
}

entity "description" as description {
  eng : string
  hind : string
}

entity "subTasks" as subTasks {
  name : string
  namehindi : string
}

' // Relationships
Fixed_Tasks_1 ||--|| escalations : has_escalations
escalations ||--|| Level_1 : has_Level 1
escalations ||--|| Level_2 : has_Level 2
escalations ||--|| Level_3 : has_Level 3
Fixed_Tasks_1 ||--|| heading : has_heading
Fixed_Tasks_1 ||--|| description : has_description
Fixed_Tasks_1 ||--o{ subTasks : has_subTasks
@enduml