@startuml flocsamples_Diagram

entity "flocsamples" as flocsamples {
  _id : ObjectId
  isDefault : boolean
  hide : boolean
  timeRange : list
  marks : list
  sensorId : ObjectId
  startTime : object
  endTime : object
  createdAt : object
  updatedAt : object
  __v : int
  isArchived : boolean
}

entity "marks" as marks {
  mark : string
  timestamp : object
  _id : ObjectId
}

entity "timestamp" as timestamp {
}

entity "startTime" as startTime {
}

entity "endTime" as endTime {
}

entity "createdAt" as createdAt {
}

entity "updatedAt" as updatedAt {
}

' // Relationships
flocsamples ||--o{ marks : has_marks
marks ||--|| timestamp : has_timestamp
flocsamples ||--|| startTime : has_startTime
flocsamples ||--|| endTime : has_endTime
flocsamples ||--|| createdAt : has_createdAt
flocsamples ||--|| updatedAt : has_updatedAt
@enduml