@startuml FORMULA_AUDITS_Diagram

entity "FORMULA AUDITS" as FORMULA_AUDITS {
  _id : objectId
  version : int
  name : string
  description : string
  createdBy : objectId
  plantId : objectId
  unit : string
  userGroupId : objectId
  workspaceId : objectId
  formulaTag : string
  formulaChips : list
  applyToHistoricalData : boolean
  variableList : list
  isArchived : boolean
  frequency : object
  type : string
  nextCalculationTime : int
  sensorSettingIds : list
  formulaSensorId : objectId
  __v : int
  createdAt : object
  updatedAt : object
}

entity "FORMULA CHIPS" as FORMULA_CHIPS {
  value : string
  type : string
  color : string
  sensorSetting : object
  _id : objectId
}

entity "SENSOR SETTING" as SENSOR_SETTING {
  sensorId : string
  sensorTag : string
  granularity : string
  aggregation : string
  firstReferenceTimeInMinutes : int
  lastReferenceTimeInMinutes : int
  returnType : string
  _id : objectId
}

entity "FREQUENCY" as FREQUENCY {
  dateTime : int
  timeInMinutes : int
  _id : objectId
}

entity "SENSOR SETTING IDS" as SENSOR_SETTING_IDS {
  buffer : binary
}

entity "CREATED AT" as CREATED_AT {
}

entity "UPDATED AT" as UPDATED_AT {
}

' // Relationships
FORMULA_AUDITS ||--o{ FORMULA_CHIPS : has_formulaChips
FORMULA_CHIPS ||--|| SENSOR_SETTING : has_sensorSetting
FORMULA_AUDITS ||--|| FREQUENCY : has_frequency
FORMULA_AUDITS ||--o{ SENSOR_SETTING_IDS : has_sensorSettingIds
FORMULA_AUDITS ||--|| CREATED_AT : has_createdAt
FORMULA_AUDITS ||--|| UPDATED_AT : has_updatedAt
@enduml