@startuml formulas_Diagram

entity "formulas" as formulas {
  _id : ObjectId
  variableList : list
  isArchived : boolean
  sensorSettingIds : list
  formulaChips : list
  nextCalculationTime : int
  version : int
  name : string
  description : string
  userGroupId : ObjectId
  createdBy : ObjectId
  plantId : ObjectId
  unit : string
  workspaceId : ObjectId
  formulaTag : string
  applyToHistoricalData : boolean
  frequency : object
  type : string
  formulaSensorId : ObjectId
  createdAt : object
  updatedAt : object
  __v : int
}

entity "sensorSettingIds" as sensorSettingIds {
  _id : ObjectId
}

entity "formulaChips" as formulaChips {
  value : string
  type : string
  color : string
  sensorSetting : object
  _id : ObjectId
}

entity "sensorSetting" as sensorSetting {
  sensorId : string
  sensorTag : string
  granularity : string
  aggregation : string
  firstReferenceTimeInMinutes : int
  lastReferenceTimeInMinutes : int
  returnType : string
  _id : ObjectId
}

entity "frequency" as frequency {
  dateTime : int
  timeInMinutes : int
  _id : ObjectId
}

entity "createdAt" as createdAt {
}

entity "updatedAt" as updatedAt {
}

' // Relationships
formulas ||--o{ sensorSettingIds : has_sensorSettingIds
formulas ||--o{ formulaChips : has_formulaChips
formulaChips ||--|| sensorSetting : has_sensorSetting
formulas ||--|| frequency : has_frequency
formulas ||--|| createdAt : has_createdAt
formulas ||--|| updatedAt : has_updatedAt
@enduml