@startuml GLOBAL_FORMULAS_AND_VARIABLES_Diagram

entity "GLOBAL FORMULAS AND VARIABLES" as GLOBAL_FORMULAS_AND_VARIABLES {
  _id : objectId
  lhs : string
  rhs : string
  tag : string
  variableList : list
  type : string
  isVirtualSensor : boolean
  priorityNum : int
}

@enduml