@startuml HMI_BUTTONS_Diagram

entity "HMI BUTTONS" as HMI_BUTTONS {
  _id : objectId
  equipmentId : string
  hmiPrefix : string
  plantId : objectId
  sensorId : objectId
  __v : int
  hmiTag : string
  trackingSensor : objectId
}

@enduml