@startuml hmis_Diagram

entity "hmis" as hmis {
  _id : ObjectId
  plantId : ObjectId
  hmiName : string
  plcIds : list
  controlSequence : list
  __v : int
  lastDataTimeStamp : object
}

entity "plcIds" as plcIds {
  _id : ObjectId
}

entity "lastDataTimeStamp" as lastDataTimeStamp {
}

' // Relationships
hmis ||--o{ plcIds : has_plcIds
hmis ||--|| lastDataTimeStamp : has_lastDataTimeStamp
@enduml