@startuml HYPER_FORMULAS_Diagram

entity "HYPER FORMULAS" as HYPER_FORMULAS {
  _id : objectId
  functionName : string
  method : string
  parameters : list
  __v : int
  createdAt : object
  updatedAt : object
}

entity "PARAMETERS" as PARAMETERS {
  argumentType : string
  isRequired : boolean
}

entity "CREATED AT" as CREATED_AT {
}

entity "UPDATED AT" as UPDATED_AT {
}

' // Relationships
HYPER_FORMULAS ||--o{ PARAMETERS : has_parameters
HYPER_FORMULAS ||--|| CREATED_AT : has_createdAt
HYPER_FORMULAS ||--|| UPDATED_AT : has_updatedAt
@enduml