@startuml insights_templates_Diagram

entity "insights templates" as insights_templates {
  _id : ObjectId
  description : string
  equipmentTypes : list
  attachmentId : unknown
  richTextContent : string
  isArchived : boolean
  name : string
  insightClassification : string
  insightType : string
  createdAt : object
  updatedAt : object
  __v : int
}

entity "createdAt" as createdAt {
}

entity "updatedAt" as updatedAt {
}


' Relationships
insights_templates ||--|| createdAt : has_createdAt
insights_templates ||--|| updatedAt : has_updatedAt
@enduml