@startuml INSIGHT_COMPONENTS_Diagram

entity "INSIGHT COMPONENTS" as INSIGHT_COMPONENTS {
  _id : objectId
  insightTemplateId : objectId
  triggerId : objectId
  name : string
  description : string
  insightClassification : string
  insightType : string
  attachmentId : unknown
  richTextContent : string
  userGroupId : objectId
  assetId : objectId
  equipmentIds : list
  priority : int
  isDeleted : boolean
  createdAt : object
  updatedAt : object
  __v : int
}

entity "EQUIPMENT IDS" as EQUIPMENT_IDS {
  buffer : binary
}

entity "CREATED AT" as CREATED_AT {
}

entity "UPDATED AT" as UPDATED_AT {
}

' // Relationships
INSIGHT_COMPONENTS ||--o{ EQUIPMENT_IDS : has_equipmentIds
INSIGHT_COMPONENTS ||--|| CREATED_AT : has_createdAt
INSIGHT_COMPONENTS ||--|| UPDATED_AT : has_updatedAt
@enduml