@startuml Inventory_Management_Diagram

entity "Inventory Management" as Inventory_Management {
  _id : ObjectId
  plant_id : string
  plant_inventory : list
}

entity "plant inventory" as plant_inventory {
  inventory_list : list
  inventory : string
}

entity "inventory list" as inventory_list {
  product_data : object
  product_id : string
}

entity "product data" as product_data {
  quantity : object
  remarks : object
}

entity "quantity" as quantity {
  total : int
  current_balance : int
  unit : string
}

entity "remarks" as remarks {
  add : list
  remove : list
}


' Relationships
Inventory_Management ||--o{ plant_inventory : has_plant_inventory
plant_inventory ||--o{ inventory_list : has_inventory_list
inventory_list ||--|| product_data : has_product_data
product_data ||--|| quantity : has_quantity
product_data ||--|| remarks : has_remarks
@enduml