@startuml INVENTORY_DIFORM_Diagram

entity "INVENTORY DIFORM" as INVENTORY_DIFORM {
  _id : objectId
  plantId : objectId
  form : object
}

entity "FORM" as FORM {
  formName : string
  timeInputRequired : boolean
  clearSection : boolean
  lastUpdated : string
  questionBank : object
}

entity "QUESTION BANK" as QUESTION_BANK {
  Chemicals : object
  Consumables : object
}

entity "CHEMICALS" as CHEMICALS {
  nickName : unknown
  questions : list
}

entity "QUESTIONS" as QUESTIONS {
  title : string
  min : string
  max : int
  range : boolean
  criticalLowerLevel : int
  checked : boolean
  type : string
  sensorType : string
  sensorTypeAbr : string
  sensorTag : string
  sensorNickName : unknown
  currentValue : unknown
  previousValue : string
  prevTimeDataStored : string
  time : string
  sensorId : objectId
}

entity "CONSUMABLES" as CONSUMABLES {
  nickName : unknown
  questions : list
}

' // Relationships
INVENTORY_DIFORM ||--|| FORM : has_form
FORM ||--|| QUESTION_BANK : has_questionBank
QUESTION_BANK ||--|| CHEMICALS : has_Chemicals
CHEMICALS ||--o{ QUESTIONS : has_questions
QUESTION_BANK ||--|| CONSUMABLES : has_Consumables
CONSUMABLES ||--o{ QUESTIONS : has_questions
@enduml