@startuml Inventory_Diagram

entity "Inventory" as Inventory {
  _id : ObjectId
  name : string
  data : list
}

entity "data" as data {
  _id : ObjectId
  product_name : string
  unit : string
}


' Relationships
Inventory ||--o{ data : has_data
@enduml