@startuml LAB_TEST_DIFORM_Diagram

entity "LAB TEST DIFORM" as LAB_TEST_DIFORM {
  _id : objectId
  plantId : objectId
  form : object
  formConfiguration : object
}

entity "FORM" as FORM {
  formName : string
  timeInputRequired : boolean
  clearSection : boolean
  lastUpdated : string
  questionBank : object
  calculatedAt : string
}

entity "QUESTION BANK" as QUESTION_BANK {
  Treated Water Tank1 : object
}

entity "TREATED WATER TANK1" as TREATED_WATER_TANK1 {
  nickName : unknown
  questions : list
}

entity "QUESTIONS" as QUESTIONS {
  title : string
  min : int
  max : int
  checked : boolean
  type : string
  range : boolean
  sensorTypeAbr : string
  sensorType : string
  sensorTag : string
  sensorNickName : string
  currentValue : unknown
  previousValue : string
  prevTimeDataStored : unknown
  time : unknown
  sensorId : objectId
}

entity "FORM CONFIGURATION" as FORM_CONFIGURATION {
  isFormConfigured : boolean
}

' // Relationships
LAB_TEST_DIFORM ||--|| FORM : has_form
FORM ||--|| QUESTION_BANK : has_questionBank
QUESTION_BANK ||--|| TREATED_WATER_TANK1 : has_Treated Water Tank1
TREATED_WATER_TANK1 ||--o{ QUESTIONS : has_questions
LAB_TEST_DIFORM ||--|| FORM_CONFIGURATION : has_formConfiguration
@enduml