@startuml Layouts_Diagram

entity "Layouts" as Layouts {
  _id : ObjectId
  nodeId : ObjectId
  __v : int
  createdAt : object
  layout : object
  updatedAt : object
}

entity "createdAt" as createdAt {
}

entity "layout" as layout {
  cells : list
}

entity "cells" as cells {
  type : string
  attrs : object
  position : object
  size : object
  angle : int
  id : string
  z : int
}

entity "attrs" as attrs {
  label : object
}

entity "label" as label {
  text : string
}

entity "position" as position {
  x : int
  y : int
}

entity "size" as size {
  width : int
  height : int
}

entity "updatedAt" as updatedAt {
}


' Relationships
Layouts ||--|| createdAt : has_createdAt
Layouts ||--|| layout : has_layout
layout ||--o{ cells : has_cells
cells ||--|| attrs : has_attrs
attrs ||--|| label : has_label
cells ||--|| position : has_position
cells ||--|| size : has_size
Layouts ||--|| updatedAt : has_updatedAt
@enduml