@startuml Live_Tasks_1_Diagram

entity "Live Tasks 1" as Live_Tasks_1 {
  _id : ObjectId
  toUser : string
  plantId : ObjectId
  taskId : ObjectId
  history : list
  timeLine : list
  subTaskStatus : list
  taskType : string
  ticket : boolean
  order : int
}

entity "history" as history {
  status : string
  overDue : boolean
  completedBy : ObjectId
  escalationLevel : string
  createdAt : string
  completedAt : string
}

entity "timeLine" as timeLine {
  time : string
  event : string
  message : string
}

entity "subTaskStatus" as subTaskStatus {
  status : string
  completedBy : string
}

' // Relationships
Live_Tasks_1 ||--o{ history : has_history
Live_Tasks_1 ||--o{ timeLine : has_timeLine
Live_Tasks_1 ||--o{ subTaskStatus : has_subTaskStatus
@enduml