@startuml maintenanceDIForm_Diagram

entity "maintenanceDIForm" as maintenanceDIForm {
  _id : ObjectId
  plantId : ObjectId
  form : object
  formConfiguration : object
}

entity "form" as form {
  formName : string
  timeInputRequired : boolean
  clearSection : boolean
  lastUpdated : string
  questionBank : object
  calculatedAt : string
}

entity "questionBank" as questionBank {
  Blower1 : object
  Blower2 : object
  Blower3 : object
  Pump1 : object
  Pump2 : object
  Pump3 : object
  Pump4 : object
  Pump5 : object
  Pump6 : object
  Pump7 : object
  Pump8 : object
  Pump9 : object
  Pump10 : object
  Pump11 : object
  Pump12 : object
  Pump13 : object
  Pump14 : object
  Header1 : object
  Flowmeter1 : object
  Flowmeter2 : object
  Flowmeter3 : object
  Valves1 : object
  Bar Screen Chamber1 : object
  Filter Press1 : object
  Softner1 : object
  MGF1 : object
  ACF1 : object
}

entity "Blower1" as Blower1 {
  nickName : string
  questions : list
}

entity "questions" as questions {
  title : string
  type : string
  checked : boolean
  sensorTypeAbr : string
  sensorType : string
  sensorTag : string
  sensorNickName : unknown
  currentValue : unknown
  previousValue : boolean
  prevTimeDataStored : string
  time : string
  sensorId : ObjectId
}

entity "Blower2" as Blower2 {
  nickName : string
  questions : list
}

entity "Blower3" as Blower3 {
  nickName : string
  questions : list
}

entity "Pump1" as Pump1 {
  nickName : string
  questions : list
}

entity "Pump2" as Pump2 {
  nickName : string
  questions : list
}

entity "Pump3" as Pump3 {
  nickName : string
  questions : list
}

entity "Pump4" as Pump4 {
  nickName : string
  questions : list
}

entity "Pump5" as Pump5 {
  nickName : string
  questions : list
}

entity "Pump6" as Pump6 {
  nickName : string
  questions : list
}

entity "Pump7" as Pump7 {
  nickName : string
  questions : list
}

entity "Pump8" as Pump8 {
  nickName : string
  questions : list
}

entity "Pump9" as Pump9 {
  nickName : string
  questions : list
}

entity "Pump10" as Pump10 {
  nickName : string
  questions : list
}

entity "Pump11" as Pump11 {
  nickName : string
  questions : list
}

entity "Pump12" as Pump12 {
  nickName : string
  questions : list
}

entity "Pump13" as Pump13 {
  nickName : string
  questions : list
}

entity "Pump14" as Pump14 {
  nickName : string
  questions : list
}

entity "Header1" as Header1 {
  nickName : unknown
  questions : list
}

entity "Flowmeter1" as Flowmeter1 {
  nickName : string
  questions : list
}

entity "Flowmeter2" as Flowmeter2 {
  nickName : string
  questions : list
}

entity "Flowmeter3" as Flowmeter3 {
  nickName : string
  questions : list
}

entity "Valves1" as Valves1 {
  nickName : string
  questions : list
}

entity "Bar Screen Chamber1" as Bar_Screen_Chamber1 {
  nickName : unknown
  questions : list
}

entity "Filter Press1" as Filter_Press1 {
  nickName : unknown
  questions : list
}

entity "Softner1" as Softner1 {
  nickName : unknown
  questions : list
}

entity "MGF1" as MGF1 {
  nickName : unknown
  questions : list
}

entity "ACF1" as ACF1 {
  nickName : unknown
  questions : list
}

entity "formConfiguration" as formConfiguration {
  isFormConfigured : boolean
}


' Shared Plant entity
entity "Plants" as Plants {
  _id : ObjectId
}

' Relationships
maintenanceDIForm }o--|| Plants : refers_to
maintenanceDIForm ||--|| form : has_form
form ||--|| questionBank : has_questionBank
questionBank ||--|| Blower1 : has_Blower1
Blower1 ||--o{ questions : has_questions
questionBank ||--|| Blower2 : has_Blower2
Blower2 ||--o{ questions : has_questions
questionBank ||--|| Blower3 : has_Blower3
Blower3 ||--o{ questions : has_questions
questionBank ||--|| Pump1 : has_Pump1
Pump1 ||--o{ questions : has_questions
questionBank ||--|| Pump2 : has_Pump2
Pump2 ||--o{ questions : has_questions
questionBank ||--|| Pump3 : has_Pump3
Pump3 ||--o{ questions : has_questions
questionBank ||--|| Pump4 : has_Pump4
Pump4 ||--o{ questions : has_questions
questionBank ||--|| Pump5 : has_Pump5
Pump5 ||--o{ questions : has_questions
questionBank ||--|| Pump6 : has_Pump6
Pump6 ||--o{ questions : has_questions
questionBank ||--|| Pump7 : has_Pump7
Pump7 ||--o{ questions : has_questions
questionBank ||--|| Pump8 : has_Pump8
Pump8 ||--o{ questions : has_questions
questionBank ||--|| Pump9 : has_Pump9
Pump9 ||--o{ questions : has_questions
questionBank ||--|| Pump10 : has_Pump10
Pump10 ||--o{ questions : has_questions
questionBank ||--|| Pump11 : has_Pump11
Pump11 ||--o{ questions : has_questions
questionBank ||--|| Pump12 : has_Pump12
Pump12 ||--o{ questions : has_questions
questionBank ||--|| Pump13 : has_Pump13
Pump13 ||--o{ questions : has_questions
questionBank ||--|| Pump14 : has_Pump14
Pump14 ||--o{ questions : has_questions
questionBank ||--|| Header1 : has_Header1
Header1 ||--o{ questions : has_questions
questionBank ||--|| Flowmeter1 : has_Flowmeter1
Flowmeter1 ||--o{ questions : has_questions
questionBank ||--|| Flowmeter2 : has_Flowmeter2
Flowmeter2 ||--o{ questions : has_questions
questionBank ||--|| Flowmeter3 : has_Flowmeter3
Flowmeter3 ||--o{ questions : has_questions
questionBank ||--|| Valves1 : has_Valves1
Valves1 ||--o{ questions : has_questions
questionBank ||--|| Bar_Screen_Chamber1 : has_Bar Screen Chamber1
Bar_Screen_Chamber1 ||--o{ questions : has_questions
questionBank ||--|| Filter_Press1 : has_Filter Press1
Filter_Press1 ||--o{ questions : has_questions
questionBank ||--|| Softner1 : has_Softner1
Softner1 ||--o{ questions : has_questions
questionBank ||--|| MGF1 : has_MGF1
MGF1 ||--o{ questions : has_questions
questionBank ||--|| ACF1 : has_ACF1
ACF1 ||--o{ questions : has_questions
maintenanceDIForm ||--|| formConfiguration : has_formConfiguration
@enduml