@startuml MANUAL_ALERTS_Diagram

entity "MANUAL ALERTS" as MANUAL_ALERTS {
  _id : objectId
  toUser : string
  condition : string
  type : string
  dueTimeFromPosting : string
  autoCalling : boolean
  equipments : unknown
  issueType : list
  isOpen : boolean
  escalations : object
  heading : object
  description : object
  subTasks : list
  plantId : objectId
  metaData : object
  attachedTickets : list
  ccUsers : list
  checked : boolean
  primaryUser : object
  verifiedClosed : boolean
}

entity "ESCALATIONS" as ESCALATIONS {
  Level 1 : object
  Level 2 : object
  Level 3 : object
}

entity "LEVEL 1" as LEVEL_1 {
  time : string
  group : string
}

entity "LEVEL 2" as LEVEL_2 {
  time : string
  group : string
}

entity "LEVEL 3" as LEVEL_3 {
  time : string
  group : string
}

entity "HEADING" as HEADING {
  eng : string
  hindi : string
}

entity "DESCRIPTION" as DESCRIPTION {
  eng : string
  hindi : string
}

entity "SUB TASKS" as SUB_TASKS {
  name : string
  namehindi : string
}

entity "META DATA" as META_DATA {
  createdManually : boolean
  createdBy : string
}

entity "CC USERS" as CC_USERS {
  _id : string
  role : string
  name : string
  email : string
  number : string
  plantId : list
  defaultPageId : object
}

entity "DEFAULT PAGE ID" as DEFAULT_PAGE_ID {
  62c7d90fe88eb11e6362b33c : string
  63838083547b8c18e1a3b7bd : string
  63838168547b8c18e1a3b7c1 : string
}

entity "PRIMARY USER" as PRIMARY_USER {
  _id : string
  role : string
  name : string
  email : string
  number : string
  forid : string
  plantId : list
  userStatus : string
}

' // Relationships
MANUAL_ALERTS ||--|| ESCALATIONS : has_escalations
ESCALATIONS ||--|| LEVEL_1 : has_Level 1
ESCALATIONS ||--|| LEVEL_2 : has_Level 2
ESCALATIONS ||--|| LEVEL_3 : has_Level 3
MANUAL_ALERTS ||--|| HEADING : has_heading
MANUAL_ALERTS ||--|| DESCRIPTION : has_description
MANUAL_ALERTS ||--o{ SUB_TASKS : has_subTasks
MANUAL_ALERTS ||--|| META_DATA : has_metaData
MANUAL_ALERTS ||--o{ CC_USERS : has_ccUsers
CC_USERS ||--|| DEFAULT_PAGE_ID : has_defaultPageId
MANUAL_ALERTS ||--|| PRIMARY_USER : has_primaryUser
@enduml