@startuml Master_Diagram

entity "Master" as Master {
  _id : ObjectId
  master : string
  masterData : object
}

entity "masterData" as masterData {
  Water Quality Test Result : object
  Process Observation : object
  Maintenance : object
  Lab Test : object
  Inventory : object
}

entity "Water Quality Test Result" as Water_Quality_Test_Result {
  General : list
  Tanks : list
  Pumps : list
  Blowers : list
  Flowmeter : list
  Headers : list
  Core Equipments : list
}

entity "General" as General {
  title : string
  min : int
  max : string
  checked : boolean
  type : string
  range : boolean
  options : list
  sensorType : string
  sensorTypeAbr : string
  sensorTag : string
}

entity "Tanks" as Tanks {
  title : string
  min : int
  max : int
  checked : boolean
  type : string
  range : boolean
  sensorTypeAbr : string
  sensorType : string
  sensorTag : string
}

entity "Core Equipments" as Core_Equipments {
  title : string
  min : int
  max : int
  checked : boolean
  type : string
  range : boolean
  sensorTypeAbr : string
  sensorType : string
  sensorTag : string
}

entity "Process Observation" as Process_Observation {
  General : list
}

entity "Maintenance" as Maintenance {
  General : list
  Blowers : list
  Pumps : list
  Headers : list
  Flowmeter : list
  Valves : list
  Other Sensors : list
}

entity "Blowers" as Blowers {
  title : string
  type : string
  checked : boolean
}

entity "Pumps" as Pumps {
  title : string
  type : string
  checked : boolean
}

entity "Headers" as Headers {
  title : string
  type : string
  checked : boolean
}

entity "Flowmeter" as Flowmeter {
  title : string
  type : string
  checked : boolean
}

entity "Valves" as Valves {
  title : string
  type : string
  checked : boolean
}

entity "Other Sensors" as Other_Sensors {
  title : string
  type : string
  checked : boolean
}

entity "Lab Test" as Lab_Test {
  General : list
  Tanks : list
  Pumps : list
  Blowers : list
  Flowmeter : list
  Headers : list
  Core Equipments : list
}

entity "Inventory" as Inventory {
  Chemicals : object
  Consumables : object
  Electrical Spare List : object
  Mechanical Spare List : object
  Tool List (Electrical & Mechanical) : object
  Tool for Cleaning : object
}

entity "Chemicals" as Chemicals {
  General : list
}

entity "Consumables" as Consumables {
  General : list
}

entity "Electrical Spare List" as Electrical_Spare_List {
  General : list
}

entity "Mechanical Spare List" as Mechanical_Spare_List {
  General : list
}

entity "Tool List Electrical Mechanical" as Tool_List__Electrical___Mechanical_ {
  General : list
}

entity "Tool for Cleaning" as Tool_for_Cleaning {
  General : list
}

' // Relationships
Master ||--|| masterData : has_masterData
masterData ||--|| Water_Quality_Test_Result : has_Water Quality Test Result
Water_Quality_Test_Result ||--o{ General : has_General
Water_Quality_Test_Result ||--o{ Tanks : has_Tanks
Water_Quality_Test_Result ||--o{ Core_Equipments : has_Core Equipments
masterData ||--|| Process_Observation : has_Process Observation
Process_Observation ||--o{ General : has_General
masterData ||--|| Maintenance : has_Maintenance
Maintenance ||--o{ General : has_General
Maintenance ||--o{ Blowers : has_Blowers
Maintenance ||--o{ Pumps : has_Pumps
Maintenance ||--o{ Headers : has_Headers
Maintenance ||--o{ Flowmeter : has_Flowmeter
Maintenance ||--o{ Valves : has_Valves
Maintenance ||--o{ Other_Sensors : has_Other Sensors
masterData ||--|| Lab_Test : has_Lab Test
Lab_Test ||--o{ General : has_General
Lab_Test ||--o{ Tanks : has_Tanks
Lab_Test ||--o{ Core_Equipments : has_Core Equipments
masterData ||--|| Inventory : has_Inventory
Inventory ||--|| Chemicals : has_Chemicals
Chemicals ||--o{ General : has_General
Inventory ||--|| Consumables : has_Consumables
Consumables ||--o{ General : has_General
Inventory ||--|| Electrical_Spare_List : has_Electrical Spare List
Electrical_Spare_List ||--o{ General : has_General
Inventory ||--|| Mechanical_Spare_List : has_Mechanical Spare List
Mechanical_Spare_List ||--o{ General : has_General
Inventory ||--|| Tool_List__Electrical___Mechanical_ : has_Tool List (Electrical & Mechanical)
Tool_List__Electrical___Mechanical_ ||--o{ General : has_General
Inventory ||--|| Tool_for_Cleaning : has_Tool for Cleaning
Tool_for_Cleaning ||--o{ General : has_General
@enduml