@startuml notifications_642a6e8439658f0a6001e51e_Diagram

entity "notifications 642a6e8439658f0a6001e51e" as notifications_642a6e8439658f0a6001e51e {
  _id : ObjectId
  read : boolean
  title : string
  message : string
  user : ObjectId
  to : string
  timeStamp : object
}

entity "timeStamp" as timeStamp {
}

' // Relationships
notifications_642a6e8439658f0a6001e51e ||--|| timeStamp : has_timeStamp
@enduml