@startuml NOTIFICATIONS_61765831B95CF93D546EF368_Diagram

entity "NOTIFICATIONS 61765831B95CF93D546EF368" as NOTIFICATIONS_61765831B95CF93D546EF368 {
  _id : objectId
  read : boolean
  title : string
  message : string
  user : objectId
  to : string
  timeStamp : object
}

entity "TIME STAMP" as TIME_STAMP {
}

' // Relationships
NOTIFICATIONS_61765831B95CF93D546EF368 ||--|| TIME_STAMP : has_timeStamp
@enduml