@startuml NOTIFICATIONS_65A0D52ECA86713F28B8182D_Diagram

entity "NOTIFICATIONS 65A0D52ECA86713F28B8182D" as NOTIFICATIONS_65A0D52ECA86713F28B8182D {
  _id : objectId
  read : boolean
  title : string
  message : string
  user : objectId
  to : string
  timeStamp : object
}

entity "TIME STAMP" as TIME_STAMP {
}

' // Relationships
NOTIFICATIONS_65A0D52ECA86713F28B8182D ||--|| TIME_STAMP : has_timeStamp
@enduml