@startuml notifications_6641c6d9c09cc51adba6f3c3_Diagram

entity "notifications 6641c6d9c09cc51adba6f3c3" as notifications_6641c6d9c09cc51adba6f3c3 {
  _id : ObjectId
  read : boolean
  title : string
  message : string
  user : ObjectId
  to : string
  timeStamp : object
}

entity "timeStamp" as timeStamp {
}

' // Relationships
notifications_6641c6d9c09cc51adba6f3c3 ||--|| timeStamp : has_timeStamp
@enduml