@startuml notifications_64882501bf14bbb5792ba997_Diagram

entity "notifications 64882501bf14bbb5792ba997" as notifications_64882501bf14bbb5792ba997 {
  _id : ObjectId
  read : boolean
  title : string
  message : string
  user : ObjectId
  to : string
  timeStamp : object
}

entity "timeStamp" as timeStamp {
}

' // Relationships
notifications_64882501bf14bbb5792ba997 ||--|| timeStamp : has_timeStamp
@enduml