@startuml NOTIFICATIONS_642A6E8D39658F0A6001E524_Diagram

entity "NOTIFICATIONS 642A6E8D39658F0A6001E524" as NOTIFICATIONS_642A6E8D39658F0A6001E524 {
  _id : objectId
  read : boolean
  title : string
  message : string
  user : objectId
  to : string
  timeStamp : object
}

entity "TIME STAMP" as TIME_STAMP {
}

' // Relationships
NOTIFICATIONS_642A6E8D39658F0A6001E524 ||--|| TIME_STAMP : has_timeStamp
@enduml