@startuml NOTIFICATIONS_618B5C42CF12270D003549B4_Diagram

entity "NOTIFICATIONS 618B5C42CF12270D003549B4" as NOTIFICATIONS_618B5C42CF12270D003549B4 {
  _id : objectId
  read : boolean
  title : string
  message : string
  user : objectId
  to : string
  timeStamp : object
}

entity "TIME STAMP" as TIME_STAMP {
}

' // Relationships
NOTIFICATIONS_618B5C42CF12270D003549B4 ||--|| TIME_STAMP : has_timeStamp
@enduml