@startuml notifications_647054b7bf14bbb5792b8bf6_Diagram

entity "notifications 647054b7bf14bbb5792b8bf6" as notifications_647054b7bf14bbb5792b8bf6 {
  _id : ObjectId
  read : boolean
  title : string
  message : string
  user : ObjectId
  to : string
  timeStamp : object
}

entity "timeStamp" as timeStamp {
}

' // Relationships
notifications_647054b7bf14bbb5792b8bf6 ||--|| timeStamp : has_timeStamp
@enduml