@startuml notifications_Diagram

entity "notifications" as notifications {
  _id : ObjectId
  read : boolean
  title : string
  message : string
  user : ObjectId
  to : string
  timeStamp : object
  plantId : ObjectId
}

entity "timeStamp" as timeStamp {
}


' Shared Plant entity
entity "Plants" as Plants {
  _id : ObjectId
}

' Relationships
notifications ||--|| timeStamp : has_timeStamp
notifications }o--|| Plants : refers_to
@enduml