@startuml notifications_620cf68a15f5530706eef968_Diagram

entity "notifications 620cf68a15f5530706eef968" as notifications_620cf68a15f5530706eef968 {
  _id : ObjectId
  read : boolean
  title : string
  message : string
  user : ObjectId
  to : string
  timeStamp : object
}

entity "timeStamp" as timeStamp {
}

' // Relationships
notifications_620cf68a15f5530706eef968 ||--|| timeStamp : has_timeStamp
@enduml