@startuml notifications_6594fba34df1e220fc2672f4_Diagram

entity "notifications 6594fba34df1e220fc2672f4" as notifications_6594fba34df1e220fc2672f4 {
  _id : ObjectId
  read : boolean
  title : string
  message : string
  user : ObjectId
  to : string
  timeStamp : object
}

entity "timeStamp" as timeStamp {
}

' // Relationships
notifications_6594fba34df1e220fc2672f4 ||--|| timeStamp : has_timeStamp
@enduml