@startuml NOTIFICATIONS_63F35C923FFD5468072EFAA2_Diagram

entity "NOTIFICATIONS 63F35C923FFD5468072EFAA2" as NOTIFICATIONS_63F35C923FFD5468072EFAA2 {
  _id : objectId
  read : boolean
  title : string
  message : string
  showToUser : boolean
  user : objectId
  to : string
  isCritical : boolean
  timeStamp : object
}

entity "TIME STAMP" as TIME_STAMP {
}

' // Relationships
NOTIFICATIONS_63F35C923FFD5468072EFAA2 ||--|| TIME_STAMP : has_timeStamp
@enduml