@startuml notifications_Diagram

entity "notifications" as notifications {
  _id : ObjectId
  read : boolean
  title : string
  message : string
  user : ObjectId
  to : string
  timeStamp : object
  plantId : ObjectId
}

entity "timeStamp" as timeStamp {
}

' // Relationships
notifications ||--|| timeStamp : has_timeStamp
@enduml