@startuml notifications_65dc71673c091cada3908577_Diagram

entity "notifications 65dc71673c091cada3908577" as notifications_65dc71673c091cada3908577 {
  _id : ObjectId
  read : boolean
  title : string
  message : string
  user : ObjectId
  to : string
  timeStamp : object
}

entity "timeStamp" as timeStamp {
}

' // Relationships
notifications_65dc71673c091cada3908577 ||--|| timeStamp : has_timeStamp
@enduml