@startuml notifications6641c6d9c09cc51adba6f3c3_Diagram

entity "notifications6641c6d9c09cc51adba6f3c3" as notifications6641c6d9c09cc51adba6f3c3 {
  _id : ObjectId
  read : boolean
  title : string
  message : string
  showToUser : boolean
  user : ObjectId
  to : string
  isCritical : boolean
  timeStamp : object
}

entity "timeStamp" as timeStamp {
}

' // Relationships
notifications6641c6d9c09cc51adba6f3c3 ||--|| timeStamp : has_timeStamp
@enduml