@startuml Notifications_62c7d90fe88eb11e6362b33c_Diagram

entity "Notifications 62c7d90fe88eb11e6362b33c" as Notifications_62c7d90fe88eb11e6362b33c {
  _id : ObjectId
  read : boolean
  title : string
  message : string
  user : ObjectId
  to : string
  timeStamp : string
}

@enduml