@startuml notifications_64510316bf14bbb5792b53c9_Diagram

entity "notifications 64510316bf14bbb5792b53c9" as notifications_64510316bf14bbb5792b53c9 {
  _id : ObjectId
  read : boolean
  title : string
  message : string
  user : ObjectId
  to : string
  timeStamp : object
}

entity "timeStamp" as timeStamp {
}

' // Relationships
notifications_64510316bf14bbb5792b53c9 ||--|| timeStamp : has_timeStamp
@enduml