@startuml NOTIFICATIONS_65FC6984959A296577A79CB3_Diagram

entity "NOTIFICATIONS 65FC6984959A296577A79CB3" as NOTIFICATIONS_65FC6984959A296577A79CB3 {
  _id : objectId
  read : boolean
  title : string
  message : string
  user : objectId
  to : string
  timeStamp : object
}

entity "TIME STAMP" as TIME_STAMP {
}

' // Relationships
NOTIFICATIONS_65FC6984959A296577A79CB3 ||--|| TIME_STAMP : has_timeStamp
@enduml