@startuml Notifications_618e18ce74f85a27f952dc2d_Diagram

entity "Notifications 618e18ce74f85a27f952dc2d" as Notifications_618e18ce74f85a27f952dc2d {
  _id : ObjectId
  read : boolean
  title : string
  message : string
  user : ObjectId
  to : string
  timeStamp : object
}

entity "timeStamp" as timeStamp {
}

' // Relationships
Notifications_618e18ce74f85a27f952dc2d ||--|| timeStamp : has_timeStamp
@enduml