@startuml notifications_65eb3a5cd75a9de074f442ab_Diagram

entity "notifications 65eb3a5cd75a9de074f442ab" as notifications_65eb3a5cd75a9de074f442ab {
  _id : ObjectId
  read : boolean
  title : string
  message : string
  user : ObjectId
  to : string
  timeStamp : object
}

entity "timeStamp" as timeStamp {
}

' // Relationships
notifications_65eb3a5cd75a9de074f442ab ||--|| timeStamp : has_timeStamp
@enduml