@startuml notifications_65abb782ca86713f28b82429_Diagram

entity "notifications 65abb782ca86713f28b82429" as notifications_65abb782ca86713f28b82429 {
  _id : ObjectId
  read : boolean
  title : string
  message : string
  user : ObjectId
  to : string
  timeStamp : object
}

entity "timeStamp" as timeStamp {
}

' // Relationships
notifications_65abb782ca86713f28b82429 ||--|| timeStamp : has_timeStamp
@enduml