@startuml notifications_64510318bf14bbb5792b53cf_Diagram

entity "notifications 64510318bf14bbb5792b53cf" as notifications_64510318bf14bbb5792b53cf {
  _id : ObjectId
  read : boolean
  title : string
  message : string
  user : ObjectId
  to : string
  timeStamp : object
}

entity "timeStamp" as timeStamp {
}

' // Relationships
notifications_64510318bf14bbb5792b53cf ||--|| timeStamp : has_timeStamp
@enduml