@startuml NOTIFICATIONS_618E18CE74F85A27F952DC2D_Diagram

entity "NOTIFICATIONS 618E18CE74F85A27F952DC2D" as NOTIFICATIONS_618E18CE74F85A27F952DC2D {
  _id : objectId
  read : boolean
  title : string
  message : string
  user : objectId
  to : string
  timeStamp : object
}

entity "TIME STAMP" as TIME_STAMP {
}

' // Relationships
NOTIFICATIONS_618E18CE74F85A27F952DC2D ||--|| TIME_STAMP : has_timeStamp
@enduml