@startuml NOTIFICATIONS_617657EFB95CF93D546EF364_Diagram

entity "NOTIFICATIONS 617657EFB95CF93D546EF364" as NOTIFICATIONS_617657EFB95CF93D546EF364 {
  _id : objectId
  read : boolean
  title : string
  message : string
  user : objectId
  to : string
  timeStamp : object
}

entity "TIME STAMP" as TIME_STAMP {
}

' // Relationships
NOTIFICATIONS_617657EFB95CF93D546EF364 ||--|| TIME_STAMP : has_timeStamp
@enduml