@startuml notifications_642a6eb139658f0a6001e52c_Diagram

entity "notifications 642a6eb139658f0a6001e52c" as notifications_642a6eb139658f0a6001e52c {
  _id : ObjectId
  read : boolean
  title : string
  message : string
  user : ObjectId
  to : string
  timeStamp : object
}

entity "timeStamp" as timeStamp {
}

' // Relationships
notifications_642a6eb139658f0a6001e52c ||--|| timeStamp : has_timeStamp
@enduml