@startuml notifications_642a6e8639658f0a6001e520_Diagram

entity "notifications 642a6e8639658f0a6001e520" as notifications_642a6e8639658f0a6001e520 {
  _id : ObjectId
  read : boolean
  title : string
  message : string
  user : ObjectId
  to : string
  timeStamp : object
}

entity "timeStamp" as timeStamp {
}

' // Relationships
notifications_642a6e8639658f0a6001e520 ||--|| timeStamp : has_timeStamp
@enduml