@startuml notifications_618b5c42cf12270d003549b4_Diagram

entity "notifications 618b5c42cf12270d003549b4" as notifications_618b5c42cf12270d003549b4 {
  _id : ObjectId
  read : boolean
  title : string
  message : string
  user : ObjectId
  to : string
  timeStamp : object
}

entity "timeStamp" as timeStamp {
}

' // Relationships
notifications_618b5c42cf12270d003549b4 ||--|| timeStamp : has_timeStamp
@enduml