@startuml NOTIFICATIONS_64A2CFF6E559D86C2309530E_Diagram

entity "NOTIFICATIONS 64A2CFF6E559D86C2309530E" as NOTIFICATIONS_64A2CFF6E559D86C2309530E {
  _id : objectId
  read : boolean
  title : string
  message : string
  user : objectId
  to : string
  timeStamp : object
}

entity "TIME STAMP" as TIME_STAMP {
}

' // Relationships
NOTIFICATIONS_64A2CFF6E559D86C2309530E ||--|| TIME_STAMP : has_timeStamp
@enduml