@startuml NOTIFICATIONS_66151539C8B2C9C00C4FEE68_Diagram

entity "NOTIFICATIONS 66151539C8B2C9C00C4FEE68" as NOTIFICATIONS_66151539C8B2C9C00C4FEE68 {
  _id : objectId
  read : boolean
  title : string
  message : string
  user : objectId
  to : string
  timeStamp : object
}

entity "TIME STAMP" as TIME_STAMP {
}

' // Relationships
NOTIFICATIONS_66151539C8B2C9C00C4FEE68 ||--|| TIME_STAMP : has_timeStamp
@enduml