@startuml notifications_617657efb95cf93d546ef364_Diagram

entity "notifications 617657efb95cf93d546ef364" as notifications_617657efb95cf93d546ef364 {
  _id : ObjectId
  read : boolean
  title : string
  message : string
  user : ObjectId
  to : string
  timeStamp : object
}

entity "timeStamp" as timeStamp {
}

' // Relationships
notifications_617657efb95cf93d546ef364 ||--|| timeStamp : has_timeStamp
@enduml