@startuml notifications_6481801fbf14bbb5792ba0fa_Diagram

entity "notifications 6481801fbf14bbb5792ba0fa" as notifications_6481801fbf14bbb5792ba0fa {
  _id : ObjectId
  read : boolean
  title : string
  message : string
  user : ObjectId
  to : string
  timeStamp : object
}

entity "timeStamp" as timeStamp {
}

' // Relationships
notifications_6481801fbf14bbb5792ba0fa ||--|| timeStamp : has_timeStamp
@enduml