@startuml notifications_64a2cff6e559d86c2309530e_Diagram

entity "notifications 64a2cff6e559d86c2309530e" as notifications_64a2cff6e559d86c2309530e {
  _id : ObjectId
  read : boolean
  title : string
  message : string
  user : ObjectId
  to : string
  timeStamp : object
}

entity "timeStamp" as timeStamp {
}

' // Relationships
notifications_64a2cff6e559d86c2309530e ||--|| timeStamp : has_timeStamp
@enduml