@startuml NOTIFICATIONS_64AC048D2480C2870856050C_Diagram

entity "NOTIFICATIONS 64AC048D2480C2870856050C" as NOTIFICATIONS_64AC048D2480C2870856050C {
  _id : objectId
  read : boolean
  title : string
  message : string
  user : objectId
  to : string
  timeStamp : object
}

entity "TIME STAMP" as TIME_STAMP {
}

' // Relationships
NOTIFICATIONS_64AC048D2480C2870856050C ||--|| TIME_STAMP : has_timeStamp
@enduml