@startuml notifications_642a6fe039658f0a6001e530_Diagram

entity "notifications 642a6fe039658f0a6001e530" as notifications_642a6fe039658f0a6001e530 {
  _id : ObjectId
  read : boolean
  title : string
  message : string
  user : ObjectId
  to : string
  timeStamp : object
}

entity "timeStamp" as timeStamp {
}

' // Relationships
notifications_642a6fe039658f0a6001e530 ||--|| timeStamp : has_timeStamp
@enduml