@startuml NOTIFICATIONS_64510316BF14BBB5792B53C9_Diagram

entity "NOTIFICATIONS 64510316BF14BBB5792B53C9" as NOTIFICATIONS_64510316BF14BBB5792B53C9 {
  _id : objectId
  read : boolean
  title : string
  message : string
  user : objectId
  to : string
  timeStamp : object
}

entity "TIME STAMP" as TIME_STAMP {
}

' // Relationships
NOTIFICATIONS_64510316BF14BBB5792B53C9 ||--|| TIME_STAMP : has_timeStamp
@enduml