@startuml notifications_63838168547b8c18e1a3b7c1_Diagram

entity "notifications 63838168547b8c18e1a3b7c1" as notifications_63838168547b8c18e1a3b7c1 {
  _id : ObjectId
  read : boolean
  title : string
  message : string
  user : ObjectId
  to : string
  timeStamp : object
  showToUser : boolean
  __v : int
}

entity "timeStamp" as timeStamp {
}

' // Relationships
notifications_63838168547b8c18e1a3b7c1 ||--|| timeStamp : has_timeStamp
@enduml