@startuml notifications_65d4e5103c091cada390794a_Diagram

entity "notifications 65d4e5103c091cada390794a" as notifications_65d4e5103c091cada390794a {
  _id : ObjectId
  read : boolean
  title : string
  message : string
  user : ObjectId
  to : string
  timeStamp : object
}

entity "timeStamp" as timeStamp {
}

' // Relationships
notifications_65d4e5103c091cada390794a ||--|| timeStamp : has_timeStamp
@enduml