@startuml NOTIFICATIONS_642A6E8639658F0A6001E520_Diagram

entity "NOTIFICATIONS 642A6E8639658F0A6001E520" as NOTIFICATIONS_642A6E8639658F0A6001E520 {
  _id : objectId
  read : boolean
  title : string
  message : string
  user : objectId
  to : string
  timeStamp : object
}

entity "TIME STAMP" as TIME_STAMP {
}

' // Relationships
NOTIFICATIONS_642A6E8639658F0A6001E520 ||--|| TIME_STAMP : has_timeStamp
@enduml