@startuml notifications_63dbaed0a09252522dd4339c_Diagram

entity "notifications 63dbaed0a09252522dd4339c" as notifications_63dbaed0a09252522dd4339c {
  _id : ObjectId
  read : boolean
  title : string
  message : string
  user : ObjectId
  to : string
  timeStamp : object
}

entity "timeStamp" as timeStamp {
}

' // Relationships
notifications_63dbaed0a09252522dd4339c ||--|| timeStamp : has_timeStamp
@enduml