@startuml notifications_62a075f5717043068c8fc65b_Diagram

entity "notifications 62a075f5717043068c8fc65b" as notifications_62a075f5717043068c8fc65b {
  _id : ObjectId
  read : boolean
  title : string
  message : string
  user : ObjectId
  to : string
  timeStamp : object
}

entity "timeStamp" as timeStamp {
}

' // Relationships
notifications_62a075f5717043068c8fc65b ||--|| timeStamp : has_timeStamp
@enduml