@startuml NOTIFICATIONS_65DC71903C091CADA390857A_Diagram

entity "NOTIFICATIONS 65DC71903C091CADA390857A" as NOTIFICATIONS_65DC71903C091CADA390857A {
  _id : objectId
  read : boolean
  title : string
  message : string
  user : objectId
  to : string
  timeStamp : object
}

entity "TIME STAMP" as TIME_STAMP {
}

' // Relationships
NOTIFICATIONS_65DC71903C091CADA390857A ||--|| TIME_STAMP : has_timeStamp
@enduml