@startuml NOTIFICATIONS_63DBAED0A09252522DD4339C_Diagram

entity "NOTIFICATIONS 63DBAED0A09252522DD4339C" as NOTIFICATIONS_63DBAED0A09252522DD4339C {
  _id : objectId
  read : boolean
  title : string
  message : string
  user : objectId
  to : string
  timeStamp : object
}

entity "TIME STAMP" as TIME_STAMP {
}

' // Relationships
NOTIFICATIONS_63DBAED0A09252522DD4339C ||--|| TIME_STAMP : has_timeStamp
@enduml