@startuml notifications_64ac048d2480c2870856050c_Diagram

entity "notifications 64ac048d2480c2870856050c" as notifications_64ac048d2480c2870856050c {
  _id : ObjectId
  read : boolean
  title : string
  message : string
  user : ObjectId
  to : string
  timeStamp : object
}

entity "timeStamp" as timeStamp {
}

' // Relationships
notifications_64ac048d2480c2870856050c ||--|| timeStamp : has_timeStamp
@enduml