@startuml NOTIFICATIONS_63838168547B8C18E1A3B7C1_Diagram

entity "NOTIFICATIONS 63838168547B8C18E1A3B7C1" as NOTIFICATIONS_63838168547B8C18E1A3B7C1 {
  _id : objectId
  read : boolean
  title : string
  message : string
  user : objectId
  to : string
  timeStamp : object
  showToUser : boolean
  __v : int
}

entity "TIME STAMP" as TIME_STAMP {
}

' // Relationships
NOTIFICATIONS_63838168547B8C18E1A3B7C1 ||--|| TIME_STAMP : has_timeStamp
@enduml