@startuml notifications_660fa001c8b2c9c00c4fe6a2_Diagram

entity "notifications 660fa001c8b2c9c00c4fe6a2" as notifications_660fa001c8b2c9c00c4fe6a2 {
  _id : ObjectId
  read : boolean
  title : string
  message : string
  user : ObjectId
  to : string
  timeStamp : object
}

entity "timeStamp" as timeStamp {
}

' // Relationships
notifications_660fa001c8b2c9c00c4fe6a2 ||--|| timeStamp : has_timeStamp
@enduml