@startuml notifications_65e16b443c091cada3908c79_Diagram

entity "notifications 65e16b443c091cada3908c79" as notifications_65e16b443c091cada3908c79 {
  _id : ObjectId
  read : boolean
  title : string
  message : string
  user : ObjectId
  to : string
  timeStamp : object
}

entity "timeStamp" as timeStamp {
}

' // Relationships
notifications_65e16b443c091cada3908c79 ||--|| timeStamp : has_timeStamp
@enduml