@startuml notifications_65dc71903c091cada390857a_Diagram

entity "notifications 65dc71903c091cada390857a" as notifications_65dc71903c091cada390857a {
  _id : ObjectId
  read : boolean
  title : string
  message : string
  user : ObjectId
  to : string
  timeStamp : object
}

entity "timeStamp" as timeStamp {
}

' // Relationships
notifications_65dc71903c091cada390857a ||--|| timeStamp : has_timeStamp
@enduml