@startuml notifications_65abd6eeca86713f28b8248f_Diagram

entity "notifications 65abd6eeca86713f28b8248f" as notifications_65abd6eeca86713f28b8248f {
  _id : ObjectId
  read : boolean
  title : string
  message : string
  user : ObjectId
  to : string
  timeStamp : object
}

entity "timeStamp" as timeStamp {
}

' // Relationships
notifications_65abd6eeca86713f28b8248f ||--|| timeStamp : has_timeStamp
@enduml