@startuml notifications_62d6901b3eb0cb08a16a73cfs_Diagram

entity "notifications 62d6901b3eb0cb08a16a73cfs" as notifications_62d6901b3eb0cb08a16a73cfs {
  _id : ObjectId
  read : boolean
  title : string
  message : string
  user : ObjectId
  to : string
  timeStamp : object
  showToUser : boolean
  __v : int
}

entity "timeStamp" as timeStamp {
}

' // Relationships
notifications_62d6901b3eb0cb08a16a73cfs ||--|| timeStamp : has_timeStamp
@enduml