@startuml notifications_63838083547b8c18e1a3b7bd_Diagram

entity "notifications 63838083547b8c18e1a3b7bd" as notifications_63838083547b8c18e1a3b7bd {
  _id : ObjectId
  read : boolean
  title : string
  message : string
  user : ObjectId
  to : string
  timeStamp : object
}

entity "timeStamp" as timeStamp {
}

' // Relationships
notifications_63838083547b8c18e1a3b7bd ||--|| timeStamp : has_timeStamp
@enduml