@startuml notifications_6623022625ff8fcc86dc317f_Diagram

entity "notifications 6623022625ff8fcc86dc317f" as notifications_6623022625ff8fcc86dc317f {
  _id : ObjectId
  read : boolean
  title : string
  message : string
  user : ObjectId
  to : string
  timeStamp : object
}

entity "timeStamp" as timeStamp {
}

' // Relationships
notifications_6623022625ff8fcc86dc317f ||--|| timeStamp : has_timeStamp
@enduml