@startuml notifications_65fc6984959a296577a79cb3_Diagram

entity "notifications 65fc6984959a296577a79cb3" as notifications_65fc6984959a296577a79cb3 {
  _id : ObjectId
  read : boolean
  title : string
  message : string
  user : ObjectId
  to : string
  timeStamp : object
}

entity "timeStamp" as timeStamp {
}

' // Relationships
notifications_65fc6984959a296577a79cb3 ||--|| timeStamp : has_timeStamp
@enduml