@startuml notifications_642a6e8d39658f0a6001e524_Diagram

entity "notifications 642a6e8d39658f0a6001e524" as notifications_642a6e8d39658f0a6001e524 {
  _id : ObjectId
  read : boolean
  title : string
  message : string
  user : ObjectId
  to : string
  timeStamp : object
}

entity "timeStamp" as timeStamp {
}

' // Relationships
notifications_642a6e8d39658f0a6001e524 ||--|| timeStamp : has_timeStamp
@enduml