@startuml NOTIFICATIONS_64882501BF14BBB5792BA997_Diagram

entity "NOTIFICATIONS 64882501BF14BBB5792BA997" as NOTIFICATIONS_64882501BF14BBB5792BA997 {
  _id : objectId
  read : boolean
  title : string
  message : string
  user : objectId
  to : string
  timeStamp : object
}

entity "TIME STAMP" as TIME_STAMP {
}

' // Relationships
NOTIFICATIONS_64882501BF14BBB5792BA997 ||--|| TIME_STAMP : has_timeStamp
@enduml