@startuml notifications_6641d159c09cc51adba6f3f3_Diagram

entity "notifications 6641d159c09cc51adba6f3f3" as notifications_6641d159c09cc51adba6f3f3 {
  _id : ObjectId
  read : boolean
  title : string
  message : string
  user : ObjectId
  to : string
  timeStamp : object
}

entity "timeStamp" as timeStamp {
}

' // Relationships
notifications_6641d159c09cc51adba6f3f3 ||--|| timeStamp : has_timeStamp
@enduml