@startuml notifications_63f35c923ffd5468072efaa2_Diagram

entity "notifications 63f35c923ffd5468072efaa2" as notifications_63f35c923ffd5468072efaa2 {
  _id : ObjectId
  read : boolean
  title : string
  message : string
  showToUser : boolean
  user : ObjectId
  to : string
  isCritical : boolean
  timeStamp : object
}

entity "timeStamp" as timeStamp {
}

' // Relationships
notifications_63f35c923ffd5468072efaa2 ||--|| timeStamp : has_timeStamp
@enduml