@startuml notifications_65a0d52eca86713f28b8182d_Diagram

entity "notifications 65a0d52eca86713f28b8182d" as notifications_65a0d52eca86713f28b8182d {
  _id : ObjectId
  read : boolean
  title : string
  message : string
  user : ObjectId
  to : string
  timeStamp : object
}

entity "timeStamp" as timeStamp {
}

' // Relationships
notifications_65a0d52eca86713f28b8182d ||--|| timeStamp : has_timeStamp
@enduml