@startuml NOTIFICATIONS65C0AB709D70BA04190E07CA_Diagram

entity "NOTIFICATIONS65C0AB709D70BA04190E07CA" as NOTIFICATIONS65C0AB709D70BA04190E07CA {
  _id : objectId
  read : boolean
  title : string
  message : string
  showToUser : boolean
  user : objectId
  to : string
  isCritical : boolean
  timeStamp : object
}

entity "TIME STAMP" as TIME_STAMP {
}

' // Relationships
NOTIFICATIONS65C0AB709D70BA04190E07CA ||--|| TIME_STAMP : has_timeStamp
@enduml