@startuml NOTIFICATIONS_63838083547B8C18E1A3B7BD_Diagram

entity "NOTIFICATIONS 63838083547B8C18E1A3B7BD" as NOTIFICATIONS_63838083547B8C18E1A3B7BD {
  _id : objectId
  read : boolean
  title : string
  message : string
  user : objectId
  to : string
  timeStamp : object
}

entity "TIME STAMP" as TIME_STAMP {
}

' // Relationships
NOTIFICATIONS_63838083547B8C18E1A3B7BD ||--|| TIME_STAMP : has_timeStamp
@enduml