@startuml Notifications_62136d7fc435773ec77ec4fc_Diagram

entity "Notifications 62136d7fc435773ec77ec4fc" as Notifications_62136d7fc435773ec77ec4fc {
  _id : ObjectId
  read : boolean
  title : string
  message : string
  user : ObjectId
  to : string
  timeStamp : object
}

entity "timeStamp" as timeStamp {
}

' // Relationships
Notifications_62136d7fc435773ec77ec4fc ||--|| timeStamp : has_timeStamp
@enduml