@startuml NOTIFICATIONS_65D4E5103C091CADA390794A_Diagram

entity "NOTIFICATIONS 65D4E5103C091CADA390794A" as NOTIFICATIONS_65D4E5103C091CADA390794A {
  _id : objectId
  read : boolean
  title : string
  message : string
  user : objectId
  to : string
  timeStamp : object
}

entity "TIME STAMP" as TIME_STAMP {
}

' // Relationships
NOTIFICATIONS_65D4E5103C091CADA390794A ||--|| TIME_STAMP : has_timeStamp
@enduml