@startuml notifications_661190c5c8b2c9c00c4fea0f_Diagram

entity "notifications 661190c5c8b2c9c00c4fea0f" as notifications_661190c5c8b2c9c00c4fea0f {
  _id : ObjectId
  read : boolean
  title : string
  message : string
  user : ObjectId
  to : string
  timeStamp : object
}

entity "timeStamp" as timeStamp {
}

' // Relationships
notifications_661190c5c8b2c9c00c4fea0f ||--|| timeStamp : has_timeStamp
@enduml