@startuml notifications_65c1fe789d70ba04190e0bcd_Diagram

entity "notifications 65c1fe789d70ba04190e0bcd" as notifications_65c1fe789d70ba04190e0bcd {
  _id : ObjectId
  read : boolean
  title : string
  message : string
  user : ObjectId
  to : string
  timeStamp : object
}

entity "timeStamp" as timeStamp {
}

' // Relationships
notifications_65c1fe789d70ba04190e0bcd ||--|| timeStamp : has_timeStamp
@enduml