@startuml notifications_66151539c8b2c9c00c4fee68_Diagram

entity "notifications 66151539c8b2c9c00c4fee68" as notifications_66151539c8b2c9c00c4fee68 {
  _id : ObjectId
  read : boolean
  title : string
  message : string
  user : ObjectId
  to : string
  timeStamp : object
}

entity "timeStamp" as timeStamp {
}

' // Relationships
notifications_66151539c8b2c9c00c4fee68 ||--|| timeStamp : has_timeStamp
@enduml