@startuml notifications_647adf30bf14bbb5792b98a1_Diagram

entity "notifications 647adf30bf14bbb5792b98a1" as notifications_647adf30bf14bbb5792b98a1 {
  _id : ObjectId
  read : boolean
  title : string
  message : string
  user : ObjectId
  to : string
  timeStamp : object
}

entity "timeStamp" as timeStamp {
}

' // Relationships
notifications_647adf30bf14bbb5792b98a1 ||--|| timeStamp : has_timeStamp
@enduml