@startuml notifications_65c0ab709d70ba04190e07ca_Diagram

entity "notifications 65c0ab709d70ba04190e07ca" as notifications_65c0ab709d70ba04190e07ca {
  _id : ObjectId
  read : boolean
  title : string
  message : string
  user : ObjectId
  to : string
  timeStamp : object
}

entity "timeStamp" as timeStamp {
}

' // Relationships
notifications_65c0ab709d70ba04190e07ca ||--|| timeStamp : has_timeStamp
@enduml