@startuml NOTIFICATIONS_62D6901B3EB0CB08A16A73CFS_Diagram

entity "NOTIFICATIONS 62D6901B3EB0CB08A16A73CFS" as NOTIFICATIONS_62D6901B3EB0CB08A16A73CFS {
  _id : objectId
  read : boolean
  title : string
  message : string
  user : objectId
  to : string
  timeStamp : object
  showToUser : boolean
  __v : int
}

entity "TIME STAMP" as TIME_STAMP {
}

' // Relationships
NOTIFICATIONS_62D6901B3EB0CB08A16A73CFS ||--|| TIME_STAMP : has_timeStamp
@enduml