@startuml NOTIFICATIONS_662A31066F629E887F2C2821_Diagram

entity "NOTIFICATIONS 662A31066F629E887F2C2821" as NOTIFICATIONS_662A31066F629E887F2C2821 {
  _id : objectId
  read : boolean
  title : string
  message : string
  user : objectId
  to : string
  timeStamp : object
}

entity "TIME STAMP" as TIME_STAMP {
}

' // Relationships
NOTIFICATIONS_662A31066F629E887F2C2821 ||--|| TIME_STAMP : has_timeStamp
@enduml