@startuml notifications_62c7d90fe88eb11e6362b33cs_Diagram

entity "notifications 62c7d90fe88eb11e6362b33cs" as notifications_62c7d90fe88eb11e6362b33cs {
  _id : ObjectId
  read : boolean
  title : string
  message : string
  user : ObjectId
  to : string
  timeStamp : object
  showToUser : boolean
  __v : int
}

entity "timeStamp" as timeStamp {
}

' // Relationships
notifications_62c7d90fe88eb11e6362b33cs ||--|| timeStamp : has_timeStamp
@enduml