@startuml notifications_65e7590fd75a9de074f43ef2_Diagram

entity "notifications 65e7590fd75a9de074f43ef2" as notifications_65e7590fd75a9de074f43ef2 {
  _id : ObjectId
  read : boolean
  title : string
  message : string
  user : ObjectId
  to : string
  timeStamp : object
}

entity "timeStamp" as timeStamp {
}

' // Relationships
notifications_65e7590fd75a9de074f43ef2 ||--|| timeStamp : has_timeStamp
@enduml