@startuml NOTIFICATIONS_65C1FE789D70BA04190E0BCD_Diagram

entity "NOTIFICATIONS 65C1FE789D70BA04190E0BCD" as NOTIFICATIONS_65C1FE789D70BA04190E0BCD {
  _id : objectId
  read : boolean
  title : string
  message : string
  user : objectId
  to : string
  timeStamp : object
}

entity "TIME STAMP" as TIME_STAMP {
}

' // Relationships
NOTIFICATIONS_65C1FE789D70BA04190E0BCD ||--|| TIME_STAMP : has_timeStamp
@enduml