@startuml notifications_663c7feec09cc51adba6ead6_Diagram

entity "notifications 663c7feec09cc51adba6ead6" as notifications_663c7feec09cc51adba6ead6 {
  _id : ObjectId
  read : boolean
  title : string
  message : string
  user : ObjectId
  to : string
  timeStamp : object
}

entity "timeStamp" as timeStamp {
}

' // Relationships
notifications_663c7feec09cc51adba6ead6 ||--|| timeStamp : has_timeStamp
@enduml