@startuml notifications_6539fa4df16f206464740b28_Diagram

entity "notifications 6539fa4df16f206464740b28" as notifications_6539fa4df16f206464740b28 {
  _id : ObjectId
  read : boolean
  title : string
  message : string
  user : ObjectId
  to : string
  timeStamp : object
}

entity "timeStamp" as timeStamp {
}

' // Relationships
notifications_6539fa4df16f206464740b28 ||--|| timeStamp : has_timeStamp
@enduml