@startuml NOTIFICATIONS_647054B7BF14BBB5792B8BF6_Diagram

entity "NOTIFICATIONS 647054B7BF14BBB5792B8BF6" as NOTIFICATIONS_647054B7BF14BBB5792B8BF6 {
  _id : objectId
  read : boolean
  title : string
  message : string
  user : objectId
  to : string
  timeStamp : object
}

entity "TIME STAMP" as TIME_STAMP {
}

' // Relationships
NOTIFICATIONS_647054B7BF14BBB5792B8BF6 ||--|| TIME_STAMP : has_timeStamp
@enduml