@startuml notifications_642a6e6239658f0a6001e51b_Diagram

entity "notifications 642a6e6239658f0a6001e51b" as notifications_642a6e6239658f0a6001e51b {
  _id : ObjectId
  read : boolean
  title : string
  message : string
  user : ObjectId
  to : string
  timeStamp : object
}

entity "timeStamp" as timeStamp {
}

' // Relationships
notifications_642a6e6239658f0a6001e51b ||--|| timeStamp : has_timeStamp
@enduml