@startuml NOTIFICATIONS_642A6FE039658F0A6001E530_Diagram

entity "NOTIFICATIONS 642A6FE039658F0A6001E530" as NOTIFICATIONS_642A6FE039658F0A6001E530 {
  _id : objectId
  read : boolean
  title : string
  message : string
  user : objectId
  to : string
  timeStamp : object
}

entity "TIME STAMP" as TIME_STAMP {
}

' // Relationships
NOTIFICATIONS_642A6FE039658F0A6001E530 ||--|| TIME_STAMP : has_timeStamp
@enduml