@startuml NOTIFICATIONS_642A6EB139658F0A6001E52C_Diagram

entity "NOTIFICATIONS 642A6EB139658F0A6001E52C" as NOTIFICATIONS_642A6EB139658F0A6001E52C {
  _id : objectId
  read : boolean
  title : string
  message : string
  user : objectId
  to : string
  timeStamp : object
}

entity "TIME STAMP" as TIME_STAMP {
}

' // Relationships
NOTIFICATIONS_642A6EB139658F0A6001E52C ||--|| TIME_STAMP : has_timeStamp
@enduml