@startuml notifications_662a4e1f6f629e887f2c2826_Diagram

entity "notifications 662a4e1f6f629e887f2c2826" as notifications_662a4e1f6f629e887f2c2826 {
  _id : ObjectId
  read : boolean
  title : string
  message : string
  user : ObjectId
  to : string
  timeStamp : object
}

entity "timeStamp" as timeStamp {
}

' // Relationships
notifications_662a4e1f6f629e887f2c2826 ||--|| timeStamp : has_timeStamp
@enduml