@startuml notifications_662a31066f629e887f2c2821_Diagram

entity "notifications 662a31066f629e887f2c2821" as notifications_662a31066f629e887f2c2821 {
  _id : ObjectId
  read : boolean
  title : string
  message : string
  user : ObjectId
  to : string
  timeStamp : object
}

entity "timeStamp" as timeStamp {
}

' // Relationships
notifications_662a31066f629e887f2c2821 ||--|| timeStamp : has_timeStamp
@enduml