@startuml NOTIFICATIONS_660FA001C8B2C9C00C4FE6A2_Diagram

entity "NOTIFICATIONS 660FA001C8B2C9C00C4FE6A2" as NOTIFICATIONS_660FA001C8B2C9C00C4FE6A2 {
  _id : objectId
  read : boolean
  title : string
  message : string
  user : objectId
  to : string
  timeStamp : object
}

entity "TIME STAMP" as TIME_STAMP {
}

' // Relationships
NOTIFICATIONS_660FA001C8B2C9C00C4FE6A2 ||--|| TIME_STAMP : has_timeStamp
@enduml