@startuml NOTIFICATIONS_65E7590FD75A9DE074F43EF2_Diagram

entity "NOTIFICATIONS 65E7590FD75A9DE074F43EF2" as NOTIFICATIONS_65E7590FD75A9DE074F43EF2 {
  _id : objectId
  read : boolean
  title : string
  message : string
  user : objectId
  to : string
  timeStamp : object
}

entity "TIME STAMP" as TIME_STAMP {
}

' // Relationships
NOTIFICATIONS_65E7590FD75A9DE074F43EF2 ||--|| TIME_STAMP : has_timeStamp
@enduml