@startuml Notifications_618b8d8ecf12270d003549d4_Diagram

entity "Notifications 618b8d8ecf12270d003549d4" as Notifications_618b8d8ecf12270d003549d4 {
  _id : ObjectId
  read : boolean
  title : string
  message : string
  user : ObjectId
  to : string
  timeStamp : object
}

entity "timeStamp" as timeStamp {
}

' // Relationships
Notifications_618b8d8ecf12270d003549d4 ||--|| timeStamp : has_timeStamp
@enduml