@startuml notifications_642a6ea439658f0a6001e52a_Diagram

entity "notifications 642a6ea439658f0a6001e52a" as notifications_642a6ea439658f0a6001e52a {
  _id : ObjectId
  read : boolean
  title : string
  message : string
  user : ObjectId
  to : string
  timeStamp : object
}

entity "timeStamp" as timeStamp {
}

' // Relationships
notifications_642a6ea439658f0a6001e52a ||--|| timeStamp : has_timeStamp
@enduml