@startuml Notifications_62d6901b3eb0cb08a16a73cf_Diagram

entity "Notifications 62d6901b3eb0cb08a16a73cf" as Notifications_62d6901b3eb0cb08a16a73cf {
  _id : ObjectId
  read : boolean
  title : string
  message : string
  user : ObjectId
  to : string
  timeStamp : object
}

entity "timeStamp" as timeStamp {
}

' // Relationships
Notifications_62d6901b3eb0cb08a16a73cf ||--|| timeStamp : has_timeStamp
@enduml