@startuml NOTIFICATIONS_65ABB782CA86713F28B82429_Diagram

entity "NOTIFICATIONS 65ABB782CA86713F28B82429" as NOTIFICATIONS_65ABB782CA86713F28B82429 {
  _id : objectId
  read : boolean
  title : string
  message : string
  user : objectId
  to : string
  timeStamp : object
}

entity "TIME STAMP" as TIME_STAMP {
}

' // Relationships
NOTIFICATIONS_65ABB782CA86713F28B82429 ||--|| TIME_STAMP : has_timeStamp
@enduml