@startuml notifications_658efc6fbb92db04c79528f9_Diagram

entity "notifications 658efc6fbb92db04c79528f9" as notifications_658efc6fbb92db04c79528f9 {
  _id : ObjectId
  read : boolean
  title : string
  message : string
  user : ObjectId
  to : string
  timeStamp : object
}

entity "timeStamp" as timeStamp {
}

' // Relationships
notifications_658efc6fbb92db04c79528f9 ||--|| timeStamp : has_timeStamp
@enduml