@startuml NOTIFICATIONS_64818018BF14BBB5792BA0F7_Diagram

entity "NOTIFICATIONS 64818018BF14BBB5792BA0F7" as NOTIFICATIONS_64818018BF14BBB5792BA0F7 {
  _id : objectId
  read : boolean
  title : string
  message : string
  user : objectId
  to : string
  timeStamp : object
}

entity "TIME STAMP" as TIME_STAMP {
}

' // Relationships
NOTIFICATIONS_64818018BF14BBB5792BA0F7 ||--|| TIME_STAMP : has_timeStamp
@enduml