@startuml NOTIFICATIONS_62A075F5717043068C8FC65B_Diagram

entity "NOTIFICATIONS 62A075F5717043068C8FC65B" as NOTIFICATIONS_62A075F5717043068C8FC65B {
  _id : objectId
  read : boolean
  title : string
  message : string
  user : objectId
  to : string
  timeStamp : object
}

entity "TIME STAMP" as TIME_STAMP {
}

' // Relationships
NOTIFICATIONS_62A075F5717043068C8FC65B ||--|| TIME_STAMP : has_timeStamp
@enduml