@startuml notifications_64510318bf14bbb5792b53cb_Diagram

entity "notifications 64510318bf14bbb5792b53cb" as notifications_64510318bf14bbb5792b53cb {
  _id : ObjectId
  read : boolean
  title : string
  message : string
  user : ObjectId
  to : string
  timeStamp : object
}

entity "timeStamp" as timeStamp {
}

' // Relationships
notifications_64510318bf14bbb5792b53cb ||--|| timeStamp : has_timeStamp
@enduml