@startuml notifications_642a6e5439658f0a6001e518_Diagram

entity "notifications 642a6e5439658f0a6001e518" as notifications_642a6e5439658f0a6001e518 {
  _id : ObjectId
  read : boolean
  title : string
  message : string
  user : ObjectId
  to : string
  timeStamp : object
}

entity "timeStamp" as timeStamp {
}

' // Relationships
notifications_642a6e5439658f0a6001e518 ||--|| timeStamp : has_timeStamp
@enduml