@startuml NOTIFICATIONS_64510318BF14BBB5792B53CB_Diagram

entity "NOTIFICATIONS 64510318BF14BBB5792B53CB" as NOTIFICATIONS_64510318BF14BBB5792B53CB {
  _id : objectId
  read : boolean
  title : string
  message : string
  user : objectId
  to : string
  timeStamp : object
}

entity "TIME STAMP" as TIME_STAMP {
}

' // Relationships
NOTIFICATIONS_64510318BF14BBB5792B53CB ||--|| TIME_STAMP : has_timeStamp
@enduml