@startuml notifications_642a6e8f39658f0a6001e526_Diagram

entity "notifications 642a6e8f39658f0a6001e526" as notifications_642a6e8f39658f0a6001e526 {
  _id : ObjectId
  read : boolean
  title : string
  message : string
  user : ObjectId
  to : string
  timeStamp : object
}

entity "timeStamp" as timeStamp {
}

' // Relationships
notifications_642a6e8f39658f0a6001e526 ||--|| timeStamp : has_timeStamp
@enduml