@startuml notifications_618b8d07cf12270d003549d2_Diagram

entity "notifications 618b8d07cf12270d003549d2" as notifications_618b8d07cf12270d003549d2 {
  _id : ObjectId
  read : boolean
  title : string
  message : string
  user : ObjectId
  to : string
  timeStamp : object
  showToUser : boolean
  __v : int
}

entity "timeStamp" as timeStamp {
}

' // Relationships
notifications_618b8d07cf12270d003549d2 ||--|| timeStamp : has_timeStamp
@enduml