@startuml NOTIFICATIONS_647ADF30BF14BBB5792B98A1_Diagram

entity "NOTIFICATIONS 647ADF30BF14BBB5792B98A1" as NOTIFICATIONS_647ADF30BF14BBB5792B98A1 {
  _id : objectId
  read : boolean
  title : string
  message : string
  user : objectId
  to : string
  timeStamp : object
}

entity "TIME STAMP" as TIME_STAMP {
}

' // Relationships
NOTIFICATIONS_647ADF30BF14BBB5792B98A1 ||--|| TIME_STAMP : has_timeStamp
@enduml