@startuml NOTIFICATIONS_661190C5C8B2C9C00C4FEA0F_Diagram

entity "NOTIFICATIONS 661190C5C8B2C9C00C4FEA0F" as NOTIFICATIONS_661190C5C8B2C9C00C4FEA0F {
  _id : objectId
  read : boolean
  title : string
  message : string
  user : objectId
  to : string
  timeStamp : object
}

entity "TIME STAMP" as TIME_STAMP {
}

' // Relationships
NOTIFICATIONS_661190C5C8B2C9C00C4FEA0F ||--|| TIME_STAMP : has_timeStamp
@enduml