@startuml NOTIFICATIONS_642A6EA439658F0A6001E52A_Diagram

entity "NOTIFICATIONS 642A6EA439658F0A6001E52A" as NOTIFICATIONS_642A6EA439658F0A6001E52A {
  _id : objectId
  read : boolean
  title : string
  message : string
  user : objectId
  to : string
  timeStamp : object
}

entity "TIME STAMP" as TIME_STAMP {
}

' // Relationships
NOTIFICATIONS_642A6EA439658F0A6001E52A ||--|| TIME_STAMP : has_timeStamp
@enduml