@startuml notifications65c0ab709d70ba04190e07ca_Diagram

entity "notifications65c0ab709d70ba04190e07ca" as notifications65c0ab709d70ba04190e07ca {
  _id : ObjectId
  read : boolean
  title : string
  message : string
  showToUser : boolean
  user : ObjectId
  to : string
  isCritical : boolean
  timeStamp : object
}

entity "timeStamp" as timeStamp {
}

' // Relationships
notifications65c0ab709d70ba04190e07ca ||--|| timeStamp : has_timeStamp
@enduml