@startuml notifications_64818018bf14bbb5792ba0f7_Diagram

entity "notifications 64818018bf14bbb5792ba0f7" as notifications_64818018bf14bbb5792ba0f7 {
  _id : ObjectId
  read : boolean
  title : string
  message : string
  user : ObjectId
  to : string
  timeStamp : object
}

entity "timeStamp" as timeStamp {
}

' // Relationships
notifications_64818018bf14bbb5792ba0f7 ||--|| timeStamp : has_timeStamp
@enduml