@startuml notifications_65f845459daf9751ef9aba3d_Diagram

entity "notifications 65f845459daf9751ef9aba3d" as notifications_65f845459daf9751ef9aba3d {
  _id : ObjectId
  read : boolean
  title : string
  message : string
  user : ObjectId
  to : string
  timeStamp : object
}

entity "timeStamp" as timeStamp {
}

' // Relationships
notifications_65f845459daf9751ef9aba3d ||--|| timeStamp : has_timeStamp
@enduml