@startuml Notifications_61765831b95cf93d546ef368_Diagram

entity "Notifications 61765831b95cf93d546ef368" as Notifications_61765831b95cf93d546ef368 {
  _id : ObjectId
  read : boolean
  title : string
  message : string
  user : ObjectId
  to : string
  timeStamp : object
}

entity "timeStamp" as timeStamp {
}

' // Relationships
Notifications_61765831b95cf93d546ef368 ||--|| timeStamp : has_timeStamp
@enduml