@startuml notifications_65dc71c73c091cada390857d_Diagram

entity "notifications 65dc71c73c091cada390857d" as notifications_65dc71c73c091cada390857d {
  _id : ObjectId
  read : boolean
  title : string
  message : string
  user : ObjectId
  to : string
  timeStamp : object
}

entity "timeStamp" as timeStamp {
}

' // Relationships
notifications_65dc71c73c091cada390857d ||--|| timeStamp : has_timeStamp
@enduml