@startuml NOTIFICATIONS_642A6E8F39658F0A6001E526_Diagram

entity "NOTIFICATIONS 642A6E8F39658F0A6001E526" as NOTIFICATIONS_642A6E8F39658F0A6001E526 {
  _id : objectId
  read : boolean
  title : string
  message : string
  user : objectId
  to : string
  timeStamp : object
}

entity "TIME STAMP" as TIME_STAMP {
}

' // Relationships
NOTIFICATIONS_642A6E8F39658F0A6001E526 ||--|| TIME_STAMP : has_timeStamp
@enduml