@startuml notifications_64e7244131d8d96630885b77_Diagram

entity "notifications 64e7244131d8d96630885b77" as notifications_64e7244131d8d96630885b77 {
  _id : ObjectId
  read : boolean
  title : string
  message : string
  user : ObjectId
  to : string
  timeStamp : object
}

entity "timeStamp" as timeStamp {
}

' // Relationships
notifications_64e7244131d8d96630885b77 ||--|| timeStamp : has_timeStamp
@enduml