@startuml notifications_660fdb4ec8b2c9c00c4fe72a_Diagram

entity "notifications 660fdb4ec8b2c9c00c4fe72a" as notifications_660fdb4ec8b2c9c00c4fe72a {
  _id : ObjectId
  read : boolean
  title : string
  message : string
  user : ObjectId
  to : string
  timeStamp : object
}

entity "timeStamp" as timeStamp {
}

' // Relationships
notifications_660fdb4ec8b2c9c00c4fe72a ||--|| timeStamp : has_timeStamp
@enduml