@startuml notifications_6328165c48b60c2d9c3ac3c1_Diagram

entity "notifications 6328165c48b60c2d9c3ac3c1" as notifications_6328165c48b60c2d9c3ac3c1 {
  _id : ObjectId
  read : boolean
  title : string
  message : string
  user : ObjectId
  to : string
  timeStamp : object
}

entity "timeStamp" as timeStamp {
}

' // Relationships
notifications_6328165c48b60c2d9c3ac3c1 ||--|| timeStamp : has_timeStamp
@enduml