@startuml oldbidirectionalhistories_Diagram

entity "oldbidirectionalhistories" as oldbidirectionalhistories {
  _id : ObjectId
  plantId : ObjectId
  hmiButtons : list
  hmiButtonStates : object
  equipmentId : string
  created_at : object
  events : list
  sensorId : ObjectId
  initiated : boolean
  acknowledged : boolean
  ongoing : boolean
  underProcess : boolean
  successFull : boolean
  expiryMins : int
  __v : int
}

entity "hmiButtons" as hmiButtons {
  _id : ObjectId
  equipmentId : string
  hmiPrefix : string
  plantId : ObjectId
  sensorId : ObjectId
  __v : int
  hmiTag : string
}

entity "hmiButtonStates" as hmiButtonStates {
  BYP_EQTdd1ssMBBRdd1_2 : string
  isChanged : boolean
  MCONOFF_EQTdd1ssMBBRdd1_2 : string
}

entity "created at" as created_at {
}

entity "events" as events {
  userId : ObjectId
  command : string
  ipAddr : string
  browserDetails : string
  timestamp : object
  type : string
  _id : ObjectId
}

entity "timestamp" as timestamp {
}


' Shared Plant entity
entity "Plants" as Plants {
  _id : ObjectId
}

' Relationships
oldbidirectionalhistories }o--|| Plants : refers_to
oldbidirectionalhistories ||--o{ hmiButtons : has_hmiButtons
hmiButtons }o--|| Plants : refers_to
oldbidirectionalhistories ||--|| hmiButtonStates : has_hmiButtonStates
oldbidirectionalhistories ||--|| created_at : has_created_at
oldbidirectionalhistories ||--o{ events : has_events
events ||--|| timestamp : has_timestamp
@enduml