@startuml One_Time_Tasks_Diagram

entity "One Time Tasks" as One_Time_Tasks {
  _id : ObjectId
  toUser : string
  dueTimeFromPosting : string
  ticket : boolean
  heading : object
  description : object
  subTasks : list
  critical : boolean
  plantId : ObjectId
  equipments : object
}

entity "heading" as heading {
  eng : string
  hindi : string
}

entity "description" as description {
  eng : string
  hind : string
}

entity "subTasks" as subTasks {
  name : string
  namehindi : string
}

entity "equipments" as equipments {
  id : string
  nickName : string
  type : string
}


' Shared Plant entity
entity "Plants" as Plants {
  _id : ObjectId
}

' Relationships
One_Time_Tasks ||--|| heading : has_heading
One_Time_Tasks ||--|| description : has_description
One_Time_Tasks ||--o{ subTasks : has_subTasks
One_Time_Tasks }o--|| Plants : refers_to
One_Time_Tasks ||--|| equipments : has_equipments
@enduml