@startuml persistentnotifications_Diagram

entity "persistentnotifications" as persistentnotifications {
  _id : ObjectId
  plantId : ObjectId
  heading : string
  subHeading : string
  type : string
  read : boolean
  created_at : object
  __v : int
  userId : ObjectId
}

entity "created at" as created_at {
}

' // Relationships
persistentnotifications ||--|| created_at : has_created_at
@enduml