@startuml Plants_Diagram

entity "Plants" as Plants {
  _id : ObjectId
  plantName : string
  client : object
  csm : object
  sensors : list
  packages : list
  status : string
  renewOn : string
  lat : string
  long : string
  schematic : string
  sensorfreq : string
  plantType : string
  createdOn : string
  tur : string
  serviceProvider : object
  autoEmailing : object
  embeddedLinks : list
  abbr : string
  plantNickName : string
  pubTopic : string
  subTopic : string
  dataBreakConfig : object
  userGroup : object
}

entity "client" as client {
  id : ObjectId
  name : string
}

entity "csm" as csm {
  id : ObjectId
  name : string
}

entity "serviceProvider" as serviceProvider {
  id : unknown
  name : unknown
}

entity "autoEmailing" as autoEmailing {
  dailyReportPageId : ObjectId
  weeklyReportPageId : ObjectId
  monthlyReportPageId : ObjectId
}

entity "embeddedLinks" as embeddedLinks {
  name : string
  link : string
}

entity "dataBreakConfig" as dataBreakConfig {
  sendDataBreakAlerts : boolean
}

entity "userGroup" as userGroup {
  id : ObjectId
  name : string
  abbr : string
}


' Relationships
Plants ||--|| client : has_client
Plants ||--|| csm : has_csm
Plants ||--|| serviceProvider : has_serviceProvider
Plants ||--|| autoEmailing : has_autoEmailing
Plants ||--o{ embeddedLinks : has_embeddedLinks
Plants ||--|| dataBreakConfig : has_dataBreakConfig
Plants ||--|| userGroup : has_userGroup
@enduml