@startuml PLANT_LAYOUT_DIAGRAM_Diagram

entity "PLANT LAYOUT DIAGRAM" as PLANT_LAYOUT_DIAGRAM {
  _id : objectId
  plantId : objectId
  __v : int
  edges : list
  nodes : list
}

entity "NODES" as NODES {
  id : string
  type : string
  data : object
  _id : objectId
}

entity "DATA" as DATA {
  label : string
  configInfo : object
  image : string
  imageControlId : string
}

entity "CONFIG INFO" as CONFIG_INFO {
  id : string
  name : string
  count : int
  sensors : list
  area : float
  height : float
  free board : float
  material : string
  drain : string
  overflow : string
  bypass : string
}

entity "SENSORS" as SENSORS {
  sensorName : string
  sensorId : string
  sensorTag : string
}

' // Relationships
PLANT_LAYOUT_DIAGRAM ||--o{ NODES : has_nodes
NODES ||--|| DATA : has_data
DATA ||--|| CONFIG_INFO : has_configInfo
CONFIG_INFO ||--o{ SENSORS : has_sensors
@enduml