@startuml PLANT_FORMULAS_AND_VARS_Diagram

entity "PLANT FORMULAS AND VARS" as PLANT_FORMULAS_AND_VARS {
  _id : objectId
  plantId : objectId
  globalFormulas : list
  globalVariables : list
  customFormulas : list
}

entity "GLOBAL FORMULAS" as GLOBAL_FORMULAS {
  _id : objectId
  lhs : string
  rhs : string
  tag : string
  variableList : list
  type : string
  isVirtualSensor : boolean
  priorityNum : int
}

entity "GLOBAL VARIABLES" as GLOBAL_VARIABLES {
  _id : string
  lhs : string
  type : string
  priorityNum : int
  tag : string
  isVirtualSensor : boolean
  rhs : string
  variableList : list
}

entity "CUSTOM FORMULAS" as CUSTOM_FORMULAS {
  lhs : string
  rhs : string
  variableList : list
  type : string
  tag : string
  priorityNum : int
  isVirtualSensor : boolean
  sensorId : string
  sensorData : list
  sensorType : string
}

entity "SENSOR DATA" as SENSOR_DATA {
  _id : objectId
  sensorTag : string
  plantId : objectId
  sensorType : string
  dataType : string
  dateCreated : unknown
  sensorId : string
  sensorName : string
  sensorNickName : unknown
  plcId : objectId
  isEnabled : boolean
  oldSensorTag : string
  display : boolean
  maxValue : unknown
  minValue : unknown
  unit : unknown
}

' // Relationships
PLANT_FORMULAS_AND_VARS ||--o{ GLOBAL_FORMULAS : has_globalFormulas
PLANT_FORMULAS_AND_VARS ||--o{ GLOBAL_VARIABLES : has_globalVariables
PLANT_FORMULAS_AND_VARS ||--o{ CUSTOM_FORMULAS : has_customFormulas
CUSTOM_FORMULAS ||--o{ SENSOR_DATA : has_sensorData
@enduml