@startuml Plant_Config_Diagram

entity "Plant Config" as Plant_Config {
  _id : ObjectId
  plantId : ObjectId
  plantConfig : object
}

entity "plantConfig" as plantConfig {
  Tanks : list
  Pumps : list
  Blowers : list
  Other Sensors : list
  Headers : list
  Core Equipments : list
  Flowmeter : list
  sensorsName : object
  Valves : list
}

entity "Tanks" as Tanks {
  id : string
  name : string
  count : int
  sensors : list
  area : int
  height : int
  free board : int
  material : string
  drain : string
  overflow : string
  bypass : string
  displayNode : boolean
  _id : ObjectId
}

entity "sensors" as sensors {
  sensorName : unknown
  sensorId : string
  sensorTag : string
  sensorNickName : string
  display : boolean
  dateCreated : string
  minValue : string
  maxValue : string
}

entity "Pumps" as Pumps {
  count : int
  sensors : list
  In : list
  Out : list
  type : string
  make : string
  model : string
  motorRating : string
  nickName : string
  id : string
  onFlow : string
  pumpName : string
  tagName : string
  minHead : string
  maxHead : string
  dutyHead : string
  designFlow : string
  hmiButtons : list
  displayNode : boolean
  _id : ObjectId
}

entity "hmiButtons" as hmiButtons {
  hmiTag : string
}

entity "Blowers" as Blowers {
  id : string
  count : int
  sensors : list
  Out : list
  make : string
  model : string
  nickName : string
  rpm : string
  motorRating : string
  capacity : string
  designPressure : string
  age : string
  tagName : string
  hmiButtons : list
  displayNode : boolean
  _id : ObjectId
}

entity "Other Sensors" as Other_Sensors {
  id : string
  name : string
  count : int
  sensors : list
  displayNode : boolean
  _id : ObjectId
}

entity "Headers" as Headers {
  id : string
  count : int
  sensors : list
  Out : list
  make : string
  model : string
  displayNode : boolean
  _id : ObjectId
}

entity "Core Equipments" as Core_Equipments {
  id : string
  name : string
  count : int
  sensors : list
  displayNode : boolean
  _id : ObjectId
  nickName : string
}

entity "Flowmeter" as Flowmeter {
  id : string
  count : int
  In : list
  Out : list
  nickName : string
  sensors : list
  name : string
  displayNode : boolean
  _id : ObjectId
  EQTdd1ss : string
  ssTWTdd1 : string
}

entity "sensorsName" as sensorsName {
  Flowmeter : object
  Others : object
}

entity "Others" as Others {
  EQTdd1ss : string
  CCTdd1ssTWTdd1 : string
  ss : string
  TWTdd1ssSWTdd1 : string
  SWTdd1ss : string
}

entity "Valves" as Valves {
  id : string
  count : int
  In : list
  Out : list
  nickName : string
  age : string
  tagName : string
  sensors : list
  displayNode : boolean
  _id : ObjectId
}


' Shared Plant entity
entity "Plants" as Plants {
  _id : ObjectId
}

' Relationships
Plant_Config }o--|| Plants : refers_to
Plant_Config ||--|| plantConfig : has_plantConfig
plantConfig ||--o{ Tanks : has_Tanks
Tanks ||--o{ sensors : has_sensors
plantConfig ||--o{ Pumps : has_Pumps
Pumps ||--o{ sensors : has_sensors
Pumps ||--o{ hmiButtons : has_hmiButtons
plantConfig ||--o{ Blowers : has_Blowers
Blowers ||--o{ sensors : has_sensors
Blowers ||--o{ hmiButtons : has_hmiButtons
plantConfig ||--o{ Other_Sensors : has_Other Sensors
Other_Sensors ||--o{ sensors : has_sensors
plantConfig ||--o{ Headers : has_Headers
Headers ||--o{ sensors : has_sensors
plantConfig ||--o{ Core_Equipments : has_Core Equipments
Core_Equipments ||--o{ sensors : has_sensors
plantConfig ||--o{ Flowmeter : has_Flowmeter
Flowmeter ||--o{ sensors : has_sensors
plantConfig ||--|| sensorsName : has_sensorsName
sensorsName ||--|| Flowmeter : has_Flowmeter
sensorsName ||--|| Others : has_Others
plantConfig ||--o{ Valves : has_Valves
Valves ||--o{ sensors : has_sensors
@enduml