@startuml plcs_Diagram

entity "plcs" as plcs {
  _id : ObjectId
  nickName : string
  plantId : ObjectId
  lastUpdateTime : object
  lastMessageSentTime : object
  connectionStatus : string
  lastPinged : object
}

entity "lastUpdateTime" as lastUpdateTime {
}

entity "lastMessageSentTime" as lastMessageSentTime {
}

entity "lastPinged" as lastPinged {
}

' // Relationships
plcs ||--|| lastUpdateTime : has_lastUpdateTime
plcs ||--|| lastMessageSentTime : has_lastMessageSentTime
plcs ||--|| lastPinged : has_lastPinged
@enduml