@startuml roster_schedules_Diagram

entity "roster schedules" as roster_schedules {
  _id : ObjectId
  rosterId : ObjectId
  userId : ObjectId
  reoccurrenceId : string
  fromDate : int
  toDate : int
  slots : list
  rule : string
  color : string
  isArchived : boolean
  createdBy : ObjectId
  __v : int
  createdAt : object
  updatedAt : object
}

entity "createdAt" as createdAt {
}

entity "updatedAt" as updatedAt {
}

' // Relationships
roster_schedules ||--|| createdAt : has_createdAt
roster_schedules ||--|| updatedAt : has_updatedAt
@enduml