@startuml SENSOR_LISTS_Diagram

entity "SENSOR LISTS" as SENSOR_LISTS {
  _id : objectId
  sensorName : string
  sensorCompanyId : objectId
  sensorModelNumber : string
  granularity : list
  purpose : list
  inputType : list
  tags : list
  createdAt : object
  updatedAt : object
  __v : int
}

entity "CREATED AT" as CREATED_AT {
}

entity "UPDATED AT" as UPDATED_AT {
}

' // Relationships
SENSOR_LISTS ||--|| CREATED_AT : has_createdAt
SENSOR_LISTS ||--|| UPDATED_AT : has_updatedAt
@enduml