@startuml SENSOR_OFF_SETS_Diagram

entity "SENSOR OFF SETS" as SENSOR_OFF_SETS {
  _id : objectId
  sensorId : objectId
  plantId : objectId
  __v : int
  activity : list
  createdAt : object
  updatedAt : object
  value : int
}

entity "ACTIVITY" as ACTIVITY {
  value : int
  calculatedAtInMs : int
  userId : objectId
  createdAt : object
  _id : objectId
}

entity "CREATED AT" as CREATED_AT {
}

entity "UPDATED AT" as UPDATED_AT {
}

' // Relationships
SENSOR_OFF_SETS ||--o{ ACTIVITY : has_activity
ACTIVITY ||--|| CREATED_AT : has_createdAt
SENSOR_OFF_SETS ||--|| CREATED_AT : has_createdAt
SENSOR_OFF_SETS ||--|| UPDATED_AT : has_updatedAt
@enduml