@startuml sensors_Diagram

entity "sensors" as sensors {
  _id : ObjectId
  sensorTag : string
  plantId : ObjectId
  sensorType : string
  dateCreated : unknown
  sensorId : string
  sensorName : string
  sensorNickName : unknown
  isEnabled : boolean
  oldSensorTag : string
}


' Shared Plant entity
entity "Plants" as Plants {
  _id : ObjectId
}

' Relationships
sensors }o--|| Plants : refers_to
@enduml