@startuml SHARED_DASHBOARD_Diagram

entity "SHARED DASHBOARD" as SHARED_DASHBOARD {
  _id : objectId
  pageId : objectId
  sharedToUserId : objectId
  userId : objectId
  createdAt : object
  permissionType : string
  updatedAt : object
}

entity "CREATED AT" as CREATED_AT {
}

entity "UPDATED AT" as UPDATED_AT {
}

' // Relationships
SHARED_DASHBOARD ||--|| CREATED_AT : has_createdAt
SHARED_DASHBOARD ||--|| UPDATED_AT : has_updatedAt
@enduml