@startuml Solution_Diagram

entity "Solution" as Solution {
  _id : ObjectId
  plant_id : string
  name : string
  current_amount : int
  concentration : int
  created_date : string
  modification_date : string
}

@enduml