@startuml SOLUTIONS_Diagram

entity "SOLUTIONS" as SOLUTIONS {
  _id : objectId
  clientId : objectId
  plantId : objectId
  operatorId : objectId
  chemicalId : objectId
  solutionName : string
  chemicalQuantity : int
  waterQuantity : int
  solutionQuantity : int
  chemicalUnit : string
  solventUnit : string
  solutionPending : int
  tankId : string
  dosingMechanism : string
  solutionUsage : list
  createdOn : string
  modifiedOn : string
  __v : int
  chemicalStoreId : objectId
}

@enduml