@startuml Solutions_Diagram

entity "Solutions" as Solutions {
  _id : ObjectId
  clientId : ObjectId
  plantId : ObjectId
  operatorId : ObjectId
  chemicalId : ObjectId
  solutionName : string
  chemicalQuantity : int
  waterQuantity : int
  solutionQuantity : int
  chemicalUnit : string
  solventUnit : string
  solutionPending : int
  tankId : string
  dosingMechanism : string
  solutionUsage : list
  createdOn : string
  modifiedOn : string
  __v : int
  chemicalStoreId : ObjectId
}


' Shared Plant entity
entity "Plants" as Plants {
  _id : ObjectId
}

' Relationships
Solutions }o--|| Plants : refers_to
@enduml