@startuml SSEConnections_Diagram

entity "SSEConnections" as SSEConnections {
  _id : ObjectId
  clientId : ObjectId
  __v : int
  connectionId : object
  forAssetId : ObjectId
  lastConnected : object
  plantIds : list
}

entity "connectionId" as connectionId {
}

entity "lastConnected" as lastConnected {
}

entity "plantIds" as plantIds {
  _id : ObjectId
}

' // Relationships
SSEConnections ||--|| connectionId : has_connectionId
SSEConnections ||--|| lastConnected : has_lastConnected
SSEConnections ||--o{ plantIds : has_plantIds
@enduml