@startuml STORE_ITEMS_Diagram

entity "STORE ITEMS" as STORE_ITEMS {
  _id : objectId
  storeId : objectId
  storeCategoryName : string
  storeItemDetails : list
  createdAt : object
  updatedAt : object
  __v : int
}

entity "STORE ITEM DETAILS" as STORE_ITEM_DETAILS {
  itemId : objectId
  name : string
  min : int
  max : int
  unit : string
  assetIds : list
  expectedValue : list
  sensors : list
}

entity "ASSET IDS" as ASSET_IDS {
  buffer : binary
}

entity "EXPECTED VALUE" as EXPECTED_VALUE {
  value : int
  timeMins : int
  time : int
  timeUnit : string
  _id : objectId
}

entity "SENSORS" as SENSORS {
  buffer : binary
}

entity "CREATED AT" as CREATED_AT {
}

entity "UPDATED AT" as UPDATED_AT {
}

' // Relationships
STORE_ITEMS ||--o{ STORE_ITEM_DETAILS : has_storeItemDetails
STORE_ITEM_DETAILS ||--o{ ASSET_IDS : has_assetIds
STORE_ITEM_DETAILS ||--o{ EXPECTED_VALUE : has_expectedValue
STORE_ITEM_DETAILS ||--o{ SENSORS : has_sensors
STORE_ITEMS ||--|| CREATED_AT : has_createdAt
STORE_ITEMS ||--|| UPDATED_AT : has_updatedAt
@enduml