@startuml Stores_Diagram

entity "Stores" as Stores {
  _id : ObjectId
  name : string
  assets : list
  clients : list
  archived : boolean
  totalItems : int
  serialNo : int
  storeAbbr : string
  __v : int
}

entity "assets" as assets {
  _id : ObjectId
}


' Relationships
Stores ||--o{ assets : has_assets
@enduml