@startuml STREAM_DIFORM_Diagram

entity "STREAM DIFORM" as STREAM_DIFORM {
  _id : objectId
  plantId : objectId
  form : object
  formConfiguration : object
}

entity "FORM" as FORM {
  formName : string
  timeInputRequired : boolean
  clearSection : boolean
  lastUpdated : string
  questionBank : object
}

entity "QUESTION BANK" as QUESTION_BANK {
}

entity "FORM CONFIGURATION" as FORM_CONFIGURATION {
  isFormConfigured : boolean
}

' // Relationships
STREAM_DIFORM ||--|| FORM : has_form
FORM ||--|| QUESTION_BANK : has_questionBank
STREAM_DIFORM ||--|| FORM_CONFIGURATION : has_formConfiguration
@enduml