@startuml tags_Diagram

entity "tags" as tags {
  _id : ObjectId
  name : string
  type : string
  userId : ObjectId
  createdAt : object
  updatedAt : object
  __v : int
}

entity "createdAt" as createdAt {
}

entity "updatedAt" as updatedAt {
}


' Relationships
tags ||--|| createdAt : has_createdAt
tags ||--|| updatedAt : has_updatedAt
@enduml