@startuml task_templates_Diagram

entity "task templates" as task_templates {
  _id : ObjectId
  userGroupId : unknown
  skillsSelected : list
  dataEntry : boolean
  isArchived : boolean
  name : string
  description : string
  scope : string
  trainingVideoId : unknown
  attachmentId : ObjectId
  priority : string
  taskType : string
  workflowId : ObjectId
  taskCompletion : string
  taskCompletionState : unknown
  assigneeMethod : string
  complexity : int
  taskDeadlineTime : int
  taskExpectedTime : int
  sensorTag : string
  richTextContent : string
  createdBy : ObjectId
  createdAt : object
  updatedAt : object
  __v : int
}

entity "createdAt" as createdAt {
}

entity "updatedAt" as updatedAt {
}


' Relationships
task_templates ||--|| createdAt : has_createdAt
task_templates ||--|| updatedAt : has_updatedAt
@enduml