@startuml tickets_62136d7fc435773ec77ec4fc_Diagram

entity "tickets 62136d7fc435773ec77ec4fc" as tickets_62136d7fc435773ec77ec4fc {
  _id : ObjectId
  plantId : ObjectId
  alertId : ObjectId
  dueTimeFromPosting : string
  observationFreq : unknown
  escalations : object
  createdAt : object
  isOpen : boolean
  openingInfo : object
  closingInfo : object
  attachedSolutions : list
  events : list
}

entity "escalations" as escalations {
  Level 1 : object
  Level 2 : object
  Level 3 : object
}

entity "Level 1" as Level_1 {
  time : string
  group : string
}

entity "Level 2" as Level_2 {
  time : string
  group : string
}

entity "Level 3" as Level_3 {
  time : string
  group : string
}

entity "createdAt" as createdAt {
}

entity "openingInfo" as openingInfo {
  openedAt : object
  openedBy : ObjectId
}

entity "openedAt" as openedAt {
}

entity "closingInfo" as closingInfo {
  closedAt : object
  closedBy : ObjectId
}

entity "closedAt" as closedAt {
}

entity "events" as events {
  event : string
  message : string
  time : object
}

entity "time" as time {
}

' // Relationships
tickets_62136d7fc435773ec77ec4fc ||--|| escalations : has_escalations
escalations ||--|| Level_1 : has_Level 1
escalations ||--|| Level_2 : has_Level 2
escalations ||--|| Level_3 : has_Level 3
tickets_62136d7fc435773ec77ec4fc ||--|| createdAt : has_createdAt
tickets_62136d7fc435773ec77ec4fc ||--|| openingInfo : has_openingInfo
openingInfo ||--|| openedAt : has_openedAt
tickets_62136d7fc435773ec77ec4fc ||--|| closingInfo : has_closingInfo
closingInfo ||--|| closedAt : has_closedAt
tickets_62136d7fc435773ec77ec4fc ||--o{ events : has_events
events ||--|| time : has_time
@enduml