@startuml tickets_647adf30bf14bbb5792b98a1_Diagram

entity "tickets 647adf30bf14bbb5792b98a1" as tickets_647adf30bf14bbb5792b98a1 {
  _id : ObjectId
  plantId : ObjectId
  alertId : ObjectId
  dueTimeFromPosting : string
  observationFreq : string
  escalations : object
  createdAt : object
  isOpen : boolean
  openingInfo : object
  closingInfo : object
  attachedSolutions : list
  events : list
  preDueNotification : object
  overdue : boolean
  escalationLevel : string
  isEscalated : boolean
}

entity "escalations" as escalations {
  Level 1 : object
  Level 2 : object
  Level 3 : object
}

entity "Level 1" as Level_1 {
  time : string
  group : string
}

entity "Level 2" as Level_2 {
  time : string
  group : string
}

entity "Level 3" as Level_3 {
  time : string
  group : string
}

entity "createdAt" as createdAt {
}

entity "openingInfo" as openingInfo {
  openedAt : object
  openedBy : string
}

entity "openedAt" as openedAt {
}

entity "closingInfo" as closingInfo {
  closedAt : string
  closedBy : string
}

entity "events" as events {
  event : string
  message : string
  time : object
}

entity "time" as time {
}

entity "preDueNotification" as preDueNotification {
  Due : boolean
  Escalation Level 1 : boolean
  Escalation Level 2 : boolean
  Escalation Level 3 : boolean
}

' // Relationships
tickets_647adf30bf14bbb5792b98a1 ||--|| escalations : has_escalations
escalations ||--|| Level_1 : has_Level 1
escalations ||--|| Level_2 : has_Level 2
escalations ||--|| Level_3 : has_Level 3
tickets_647adf30bf14bbb5792b98a1 ||--|| createdAt : has_createdAt
tickets_647adf30bf14bbb5792b98a1 ||--|| openingInfo : has_openingInfo
openingInfo ||--|| openedAt : has_openedAt
tickets_647adf30bf14bbb5792b98a1 ||--|| closingInfo : has_closingInfo
tickets_647adf30bf14bbb5792b98a1 ||--o{ events : has_events
events ||--|| time : has_time
tickets_647adf30bf14bbb5792b98a1 ||--|| preDueNotification : has_preDueNotification
@enduml