@startuml tickets_65dc71673c091cada3908577_Diagram

entity "tickets 65dc71673c091cada3908577" as tickets_65dc71673c091cada3908577 {
  _id : ObjectId
  plantId : ObjectId
  alertId : ObjectId
  dueTimeFromPosting : string
  observationFreq : string
  escalations : object
  createdAt : object
  isOpen : boolean
  openingInfo : object
  closingInfo : object
  attachedSolutions : list
  events : list
  preDueNotification : object
  overdue : boolean
}

entity "escalations" as escalations {
  Level 1 : object
  Level 2 : object
  Level 3 : object
}

entity "Level 1" as Level_1 {
  time : string
  group : string
}

entity "Level 2" as Level_2 {
  time : string
  group : string
}

entity "Level 3" as Level_3 {
  time : string
  group : string
}

entity "createdAt" as createdAt {
}

entity "openingInfo" as openingInfo {
  openedAt : object
  openedBy : string
}

entity "openedAt" as openedAt {
}

entity "closingInfo" as closingInfo {
  closedAt : object
  closedBy : string
}

entity "closedAt" as closedAt {
}

entity "events" as events {
  event : string
  message : string
  time : object
}

entity "time" as time {
}

entity "preDueNotification" as preDueNotification {
  Due : boolean
}

' // Relationships
tickets_65dc71673c091cada3908577 ||--|| escalations : has_escalations
escalations ||--|| Level_1 : has_Level 1
escalations ||--|| Level_2 : has_Level 2
escalations ||--|| Level_3 : has_Level 3
tickets_65dc71673c091cada3908577 ||--|| createdAt : has_createdAt
tickets_65dc71673c091cada3908577 ||--|| openingInfo : has_openingInfo
openingInfo ||--|| openedAt : has_openedAt
tickets_65dc71673c091cada3908577 ||--|| closingInfo : has_closingInfo
closingInfo ||--|| closedAt : has_closedAt
tickets_65dc71673c091cada3908577 ||--o{ events : has_events
events ||--|| time : has_time
tickets_65dc71673c091cada3908577 ||--|| preDueNotification : has_preDueNotification
@enduml