@startuml tickets_618b5c42cf12270d003549b4_Diagram

entity "tickets 618b5c42cf12270d003549b4" as tickets_618b5c42cf12270d003549b4 {
  _id : ObjectId
  plantId : ObjectId
  alertId : ObjectId
  dueTimeFromPosting : string
  observationFreq : string
  escalations : object
  createdAt : object
  isOpen : boolean
  openingInfo : object
  closingInfo : object
  attachedSolutions : list
  events : list
  overdue : boolean
  escalationLevel : string
  isEscalated : boolean
}

entity "escalations" as escalations {
  Level 1 : object
  Level 2 : object
  Level 3 : object
}

entity "Level 1" as Level_1 {
  time : string
  group : string
}

entity "Level 2" as Level_2 {
  time : string
  group : string
}

entity "Level 3" as Level_3 {
  time : string
  group : string
}

entity "createdAt" as createdAt {
}

entity "openingInfo" as openingInfo {
  openedAt : object
  openedBy : string
}

entity "openedAt" as openedAt {
}

entity "closingInfo" as closingInfo {
  closedAt : object
  closedBy : string
}

entity "closedAt" as closedAt {
}

entity "events" as events {
  event : string
  message : string
  time : object
}

entity "time" as time {
}

' // Relationships
tickets_618b5c42cf12270d003549b4 ||--|| escalations : has_escalations
escalations ||--|| Level_1 : has_Level 1
escalations ||--|| Level_2 : has_Level 2
escalations ||--|| Level_3 : has_Level 3
tickets_618b5c42cf12270d003549b4 ||--|| createdAt : has_createdAt
tickets_618b5c42cf12270d003549b4 ||--|| openingInfo : has_openingInfo
openingInfo ||--|| openedAt : has_openedAt
tickets_618b5c42cf12270d003549b4 ||--|| closingInfo : has_closingInfo
closingInfo ||--|| closedAt : has_closedAt
tickets_618b5c42cf12270d003549b4 ||--o{ events : has_events
events ||--|| time : has_time
@enduml