@startuml tickets_Diagram

entity "tickets" as tickets {
  _id : ObjectId
  alertId : ObjectId
  dueTimeFromPosting : string
  observationFreq : unknown
  escalations : object
  createdAt : object
  isOpen : boolean
  openingInfo : object
  closingInfo : object
  attachedSolutions : list
  events : list
  plantIds : list
}

entity "escalations" as escalations {
  Level 1 : object
  Level 2 : object
  Level 3 : object
}

entity "Level 1" as Level_1 {
  time : string
  group : string
}

entity "Level 2" as Level_2 {
  time : string
  group : string
}

entity "Level 3" as Level_3 {
  time : string
  group : string
}

entity "createdAt" as createdAt {
}

entity "openingInfo" as openingInfo {
  openedAt : object
  openedBy : string
}

entity "openedAt" as openedAt {
}

entity "closingInfo" as closingInfo {
  closedAt : string
  closedBy : string
}

entity "events" as events {
  event : string
  message : string
  time : object
}

entity "time" as time {
}

entity "plantIds" as plantIds {
  _id : ObjectId
}

' // Relationships
tickets ||--|| escalations : has_escalations
escalations ||--|| Level_1 : has_Level 1
escalations ||--|| Level_2 : has_Level 2
escalations ||--|| Level_3 : has_Level 3
tickets ||--|| createdAt : has_createdAt
tickets ||--|| openingInfo : has_openingInfo
openingInfo ||--|| openedAt : has_openedAt
tickets ||--|| closingInfo : has_closingInfo
tickets ||--o{ events : has_events
events ||--|| time : has_time
tickets ||--o{ plantIds : has_plantIds
@enduml