@startuml TIME_FRAMES_Diagram

entity "TIME FRAMES" as TIME_FRAMES {
  _id : objectId
  startTime : object
  endTime : object
  for : string
  refId : objectId
  __v : int
}

entity "START TIME" as START_TIME {
}

entity "END TIME" as END_TIME {
}

' // Relationships
TIME_FRAMES ||--|| START_TIME : has_startTime
TIME_FRAMES ||--|| END_TIME : has_endTime
@enduml