@startuml timeFrames_Diagram

entity "timeFrames" as timeFrames {
  _id : ObjectId
  startTime : object
  endTime : object
  for : string
  refId : ObjectId
  __v : int
}

entity "startTime" as startTime {
}

entity "endTime" as endTime {
}

' // Relationships
timeFrames ||--|| startTime : has_startTime
timeFrames ||--|| endTime : has_endTime
@enduml