@startuml Time_Line_Backup_Diagram

entity "0" as 0 {
  time : string
  event : string
  message : string
}

entity "1" as 1 {
  time : string
  event : string
  message : string
}

entity "2" as 2 {
  time : string
  event : string
  message : string
}

entity "3" as 3 {
  time : string
  event : string
  message : string
}

entity "4" as 4 {
  time : string
  event : string
  message : string
}

entity "5" as 5 {
  time : string
  event : string
  message : string
}

entity "6" as 6 {
  time : string
  event : string
  message : string
}

entity "7" as 7 {
  time : string
  event : string
  message : string
}

entity "Time Line Backup" as Time_Line_Backup {
  _id : ObjectId
  taskId : ObjectId
  Backup : list
}

entity "Backup" as Backup {
  0 : object
  1 : object
  2 : object
  3 : object
  4 : object
  5 : object
  6 : object
  7 : object
}

' // Relationships
Time_Line_Backup ||--o{ Backup : has_Backup
Backup ||--|| 0 : has_0
Backup ||--|| 1 : has_1
Backup ||--|| 2 : has_2
Backup ||--|| 3 : has_3
Backup ||--|| 4 : has_4
Backup ||--|| 5 : has_5
Backup ||--|| 6 : has_6
Backup ||--|| 7 : has_7
@enduml