@startuml Total_Hours_Run_Diagram

entity "Total Hours Run" as Total_Hours_Run {
  _id : ObjectId
  hoursRun : object
  plantId : ObjectId
  lastUpdated : string
}

entity "hoursRun" as hoursRun {
  ONOFF_EQTdd1ssATdd1_1 : float
  ONOFF_EQTdd1ssATdd1_2 : float
  ONOFF_CCTdd1ssTWTdd1_1 : float
  ONOFF_CCTdd1ssTWTdd1_2 : float
  ONOFF_TSTdd1ssATdd1_1 : int
  ONOFF_TSTdd1ssATdd1_2 : float
  ONOFF_TWTdd1ssSWTdd1_1 : int
  ONOFF_TWTdd1ssSWTdd1_2 : int
  ONOFF_SWTdd1ssCTdd1_1 : int
  ONOFF_SWTdd1ssCTdd1_2 : int
  ONOFF_TWTdd1ssIRdd1_1 : int
  ONOFF_TWTdd1ssIRdd1_2 : float
  ONOFF_SHTdd1ssFPdd1_1 : int
  ONOFF_BLW_1 : float
  ONOFF_BLW_2 : float
  ONOFF_BLW_3 : float
  ONOFF_FP_1 : int
}


' Shared Plant entity
entity "Plants" as Plants {
  _id : ObjectId
}

' Relationships
Total_Hours_Run ||--|| hoursRun : has_hoursRun
Total_Hours_Run }o--|| Plants : refers_to
@enduml