@startuml triggers_Diagram

entity "triggers" as triggers {
  _id : ObjectId
  name : string
  description : string
  scope : string
  triggerTag : string
  assets : list
  type : string
  startDate : int
  triggerComponents : list
  createdBy : ObjectId
  triggerSensorId : ObjectId
  status : string
  isOpen : boolean
  isDeleted : boolean
  createdAt : object
  updatedAt : object
  __v : int
}

entity "createdAt" as createdAt {
}

entity "updatedAt" as updatedAt {
}


' Relationships
triggers ||--|| createdAt : has_createdAt
triggers ||--|| updatedAt : has_updatedAt
@enduml