@startuml TWILLIO_CALLS_Diagram

entity "TWILLIO CALLS" as TWILLIO_CALLS {
  _id : objectId
  message : string
  to : string
  callSid : string
  event : object
  createdAt : object
  prevCallsSids : list
  rechecking : boolean
}

entity "EVENT" as EVENT {
  alertId : objectId
  plantId : objectId
  type : string
  userId : objectId
}

entity "CREATED AT" as CREATED_AT {
}

' // Relationships
TWILLIO_CALLS ||--|| EVENT : has_event
TWILLIO_CALLS ||--|| CREATED_AT : has_createdAt
@enduml