@startuml USER_GROUPS_Diagram

entity "USER GROUPS" as USER_GROUPS {
  _id : objectId
  name : string
  description : string
  createdBy : objectId
  userIds : list
  featureTags : list
  workspaceAssets : list
  isArchived : boolean
  abbr : string
  createdAt : object
  updatedAt : object
  __v : int
}

entity "USER IDS" as USER_IDS {
  buffer : binary
}

entity "WORKSPACE ASSETS" as WORKSPACE_ASSETS {
  workspaceId : objectId
  assetIds : list
}

entity "ASSET IDS" as ASSET_IDS {
  buffer : binary
}

entity "CREATED AT" as CREATED_AT {
}

entity "UPDATED AT" as UPDATED_AT {
}

' // Relationships
USER_GROUPS ||--o{ USER_IDS : has_userIds
USER_GROUPS ||--o{ WORKSPACE_ASSETS : has_workspaceAssets
WORKSPACE_ASSETS ||--o{ ASSET_IDS : has_assetIds
USER_GROUPS ||--|| CREATED_AT : has_createdAt
USER_GROUPS ||--|| UPDATED_AT : has_updatedAt
@enduml