@startuml useraddeditems_Diagram

entity "useraddeditems" as useraddeditems {
  _id : ObjectId
  itemType : string
  assets : list
  itemData : object
  __v : int
}

entity "assets" as assets {
  _id : ObjectId
}

entity "itemData" as itemData {
  name : string
  description : string
  unit : string
  sensors : object
}

entity "sensors" as sensors {
  sensorQuant : object
  sensorConsumed : object
  sensorConsumedInPlant : object
  sensorAdd : object
}

entity "sensorQuant" as sensorQuant {
  sensorTag : string
  sensorType : string
  sensorTypeAbr : string
  type : string
}

entity "sensorConsumed" as sensorConsumed {
  sensorTag : string
  sensorType : string
  sensorTypeAbr : string
  type : string
}

entity "sensorConsumedInPlant" as sensorConsumedInPlant {
  sensorTag : string
  sensorType : string
  sensorTypeAbr : string
  type : string
}

entity "sensorAdd" as sensorAdd {
  sensorTag : string
  sensorType : string
  sensorTypeAbr : string
  type : string
}


' Relationships
useraddeditems ||--o{ assets : has_assets
useraddeditems ||--|| itemData : has_itemData
itemData ||--|| sensors : has_sensors
sensors ||--|| sensorQuant : has_sensorQuant
sensors ||--|| sensorConsumed : has_sensorConsumed
sensors ||--|| sensorConsumedInPlant : has_sensorConsumedInPlant
sensors ||--|| sensorAdd : has_sensorAdd
@enduml