@startuml userGroup_workspace_asset_user_role_Diagram

entity "userGroup workspace asset user role" as userGroup_workspace_asset_user_role {
  _id : ObjectId
  userGroupId : ObjectId
  assetId : ObjectId
  workspaceId : ObjectId
  userId : ObjectId
  roleId : ObjectId
  createdAt : object
  updatedAt : object
  __v : int
}

entity "createdAt" as createdAt {
}

entity "updatedAt" as updatedAt {
}


' Relationships
userGroup_workspace_asset_user_role ||--|| createdAt : has_createdAt
userGroup_workspace_asset_user_role ||--|| updatedAt : has_updatedAt
@enduml