@startuml WATER_QUALITY_DIFORM_Diagram

entity "WATER QUALITY DIFORM" as WATER_QUALITY_DIFORM {
  _id : objectId
  plantId : objectId
  form : object
  formConfiguration : object
}

entity "FORM" as FORM {
  formName : string
  timeInputRequired : boolean
  clearSection : boolean
  lastUpdated : string
  questionBank : object
  calculatedAt : string
}

entity "QUESTION BANK" as QUESTION_BANK {
  Equalization Tank1 : object
  Aeration Tank1 : object
  Treated Water Tank1 : object
}

entity "EQUALIZATION TANK1" as EQUALIZATION_TANK1 {
  nickName : unknown
  questions : list
}

entity "QUESTIONS" as QUESTIONS {
  title : string
  min : int
  max : int
  checked : boolean
  type : string
  range : boolean
  sensorTypeAbr : string
  sensorType : string
  sensorTag : string
  sensorNickName : string
  currentValue : unknown
  previousValue : string
  prevTimeDataStored : string
  time : string
  sensorId : objectId
}

entity "AERATION TANK1" as AERATION_TANK1 {
  nickName : unknown
  questions : list
}

entity "TREATED WATER TANK1" as TREATED_WATER_TANK1 {
  nickName : unknown
  questions : list
}

entity "FORM CONFIGURATION" as FORM_CONFIGURATION {
  isFormConfigured : boolean
}

' // Relationships
WATER_QUALITY_DIFORM ||--|| FORM : has_form
FORM ||--|| QUESTION_BANK : has_questionBank
QUESTION_BANK ||--|| EQUALIZATION_TANK1 : has_Equalization Tank1
EQUALIZATION_TANK1 ||--o{ QUESTIONS : has_questions
QUESTION_BANK ||--|| AERATION_TANK1 : has_Aeration Tank1
AERATION_TANK1 ||--o{ QUESTIONS : has_questions
QUESTION_BANK ||--|| TREATED_WATER_TANK1 : has_Treated Water Tank1
TREATED_WATER_TANK1 ||--o{ QUESTIONS : has_questions
WATER_QUALITY_DIFORM ||--|| FORM_CONFIGURATION : has_formConfiguration
@enduml