@startuml WHATSAPP_TEMPLATES_Diagram

entity "WHATSAPP TEMPLATES" as WHATSAPP_TEMPLATES {
  _id : objectId
  contentTemplateSid : string
  templateName : string
  templateContent : string
  variables : list
  isArchived : boolean
  __v : int
  createdAt : object
  updatedAt : object
}

entity "VARIABLES" as VARIABLES {
  position : int
  value : string
  _id : objectId
}

entity "CREATED AT" as CREATED_AT {
}

entity "UPDATED AT" as UPDATED_AT {
}

' // Relationships
WHATSAPP_TEMPLATES ||--o{ VARIABLES : has_variables
WHATSAPP_TEMPLATES ||--|| CREATED_AT : has_createdAt
WHATSAPP_TEMPLATES ||--|| UPDATED_AT : has_updatedAt
@enduml