@startuml widgets_Diagram

entity "widgets" as widgets {
  _id : ObjectId
  checked : boolean
  widgetType : string
  heading : object
  font : object
  position : object
  widgetOriginId : ObjectId
  dashboardPageId : ObjectId
}

entity "heading" as heading {
  english : string
  hindi : string
}

entity "font" as font {
  family : string
  color : string
  size : string
}

entity "position" as position {
}


' Relationships
widgets ||--|| heading : has_heading
widgets ||--|| font : has_font
widgets ||--|| position : has_position
@enduml