@startuml workflows_Diagram

entity "workflows" as workflows {
  _id : ObjectId
  userGroupId : ObjectId
  isArchived : boolean
  nodes : list
  edges : list
  workflowActions : list
  name : string
  description : string
  scope : string
  createdBy : ObjectId
  createdAt : object
  updatedAt : object
  __v : int
}

entity "nodes" as nodes {
  id : string
  type : string
  position : object
  data : object
  width : int
  height : int
  selected : boolean
  positionAbsolute : object
  dragging : boolean
}

entity "position" as position {
  x : float
  y : float
}

entity "data" as data {
  type : string
  label : string
}

entity "positionAbsolute" as positionAbsolute {
  x : float
  y : float
}

entity "edges" as edges {
  source : string
  sourceHandle : string
  target : string
  targetHandle : string
  id : string
  type : string
  animated : boolean
  data : object
  markerEnd : object
}

entity "markerEnd" as markerEnd {
  type : string
  width : int
  height : int
  color : string
}

entity "workflowActions" as workflowActions {
  nodeId : string
  nodeLabel : string
  actionNodes : list
  _id : ObjectId
}

entity "actionNodes" as actionNodes {
  id : string
  label : string
  selectedAction : string
  selectedActionValue : string
  _id : ObjectId
}

entity "createdAt" as createdAt {
}

entity "updatedAt" as updatedAt {
}

' // Relationships
workflows ||--o{ nodes : has_nodes
nodes ||--|| position : has_position
nodes ||--|| data : has_data
nodes ||--|| positionAbsolute : has_positionAbsolute
workflows ||--o{ edges : has_edges
edges ||--|| data : has_data
edges ||--|| markerEnd : has_markerEnd
workflows ||--o{ workflowActions : has_workflowActions
workflowActions ||--o{ actionNodes : has_actionNodes
workflows ||--|| createdAt : has_createdAt
workflows ||--|| updatedAt : has_updatedAt
@enduml