@startuml workspaces_Diagram

entity "workspaces" as workspaces {
  _id : ObjectId
  workspaceName : string
  plants : list
  client : ObjectId
  createdBy : ObjectId
  lastUpdateInfo : object
  __v : int
}

entity "plants" as plants {
  plantId : ObjectId
  diagram : object
  sensors : list
  outputs : list
  displayNode : boolean
  _id : ObjectId
}

entity "diagram" as diagram {
  imageURL : string
  imageControlId : string
  _id : ObjectId
}

entity "lastUpdateInfo" as lastUpdateInfo {
  lastUpdated : object
  lastUpdater : ObjectId
  _id : ObjectId
}

entity "lastUpdated" as lastUpdated {
}


' Shared Plant entity
entity "Plants" as Plants {
  _id : ObjectId
}

' Relationships
workspaces ||--o{ plants : has_plants
plants }o--|| Plants : refers_to
plants ||--|| diagram : has_diagram
workspaces ||--|| lastUpdateInfo : has_lastUpdateInfo
lastUpdateInfo ||--|| lastUpdated : has_lastUpdated
@enduml