
erDiagram
  "ALERT TASK" {

    string _id
    string toUser
    array condition
    string type
    string dueTimeFromPosting
    boolean isOpen
    boolean autoCalling
    object alertescalations
    object alertheading
    object alertdescription
    array alertsubTasks
    object metadata
    objectId plantId
    array attachedTickets
    array ccUsers
    string observationTime
    object primaryUser
    string resolutionFreq
    object alertequipments
    array issuetype
  }
  condition {
    string operator
    string sensorTag
    number threshold
    string thresholdType
  }
  alertescalations {
    object level
  }
  level{
    string time
    string group
  }
  alertheading{
    string eng
    string hindi
  }
  alertdescription {
    string eng
    string hind
  }
  alertsubTasks{
    string name
    string namehindi
  }
  metadata {
    string createdBy
    string createdAt
  }
  ccUsers{
    objectId _id
    string role
    string name
    string email
    string number
    objectId forid
    string password
    array plantId
    string userStatus
  }
  plantId{
    objectId plantId
  }
  primaryUser{
    objectId _id
    string forWho
    array plantId
    string name
    string number
    string email
    objectId forid
    string role
    string password
    null userStatus
  }
  attachedTickets {
    string ticketId
  }
  alertequipments{
    string id
    string nickname
    string type
  }
  "ALERT TASK" ||--o{ condition : has_conditions
  "ALERT TASK" ||--o{ alertescalations : has_escalations
  alertescalations ||--o{ level : has_levels
  "ALERT TASK" ||--|| alertheading : has_heading
  "ALERT TASK" ||--|| alertdescription : has_description
  "ALERT TASK" ||--o{ alertsubTasks : has_subTasks
  "ALERT TASK" ||--|| metadata : has_metadata
  "ALERT TASK" ||--o{ attachedTickets : has_attachedTickets
  "ALERT TASK" ||--o{ ccUsers : has_ccUsers
  ccUsers }o--o{ plantId : assigned_plants
  primaryUser ||--o{ plantId : manages_plant
  "ALERT TASK" ||--|| primaryUser : has_primaryUser
  "ALERT TASK" ||--|| alertequipments : has_equipments